# Generated by Django 5.2.9 on 2026-01-13 20:50

from django.db import migrations


def update_content_types(apps, schema_editor):
    """Update Page content_type references from mozorg to anonym ContentTypes."""
    ContentType = apps.get_model("contenttypes", "ContentType")
    Page = apps.get_model("wagtailcore", "Page")

    model_names = [
        ("anonymindexpage", "AnonymIndexPage"),
        ("anonymtopandbottompage", "AnonymTopAndBottomPage"),
        ("anonymcontentsubpage", "AnonymContentSubPage"),
        ("anonymarticlepage", "AnonymArticlePage"),
        ("anonymnewspage", "AnonymNewsPage"),
        ("anonymcontactpage", "AnonymContactPage"),
    ]

    for model_name_lower, model_name_proper in model_names:
        try:
            # Get the old mozorg ContentType
            old_ct = ContentType.objects.get(app_label="mozorg", model=model_name_lower)
            # Get or create the new anonym ContentType
            new_ct, created = ContentType.objects.get_or_create(
                app_label="anonym",
                model=model_name_lower,
            )

            # Update all Page objects that use the old ContentType
            num_updated = Page.objects.filter(content_type=old_ct).update(content_type=new_ct)

            print(f"Updated {num_updated} pages from mozorg.{model_name_lower} to anonym.{model_name_lower}")

            # Delete the old ContentType
            old_ct.delete()
            print(f"Deleted old ContentType: mozorg.{model_name_lower}")

        except ContentType.DoesNotExist:
            print(f"ContentType mozorg.{model_name_lower} not found, skipping")


def reverse_content_types(apps, schema_editor):
    """Reverse the ContentType update (for rollback)."""
    ContentType = apps.get_model("contenttypes", "ContentType")
    Page = apps.get_model("wagtailcore", "Page")

    model_names = [
        ("anonymindexpage", "AnonymIndexPage"),
        ("anonymtopandbottompage", "AnonymTopAndBottomPage"),
        ("anonymcontentsubpage", "AnonymContentSubPage"),
        ("anonymarticlepage", "AnonymArticlePage"),
        ("anonymnewspage", "AnonymNewsPage"),
        ("anonymcontactpage", "AnonymContactPage"),
    ]

    for model_name_lower, model_name_proper in model_names:
        try:
            # Get the anonym ContentType
            new_ct = ContentType.objects.get(app_label="anonym", model=model_name_lower)
            # Recreate the mozorg ContentType
            old_ct, created = ContentType.objects.get_or_create(
                app_label="mozorg",
                model=model_name_lower,
            )

            # Update all Page objects back to mozorg ContentType
            Page.objects.filter(content_type=new_ct).update(content_type=old_ct)

            # Delete the anonym ContentType if no pages use it
            if not Page.objects.filter(content_type=new_ct).exists():
                new_ct.delete()

        except ContentType.DoesNotExist:
            pass


class Migration(migrations.Migration):
    dependencies = [
        ("anonym", "0001_initial"),
        ("contenttypes", "__latest__"),
        ("wagtailcore", "__latest__"),
    ]

    operations = [
        migrations.RunPython(update_content_types, reverse_content_types),
    ]
