# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.9 on 2026-01-14 22:39

import django.db.models.deletion
from django.db import migrations, models


def update_person_content_type(apps, schema_editor):
    """Update Person content_type reference from mozorg to anonym."""
    ContentType = apps.get_model("contenttypes", "ContentType")

    try:
        # Get the old mozorg ContentType
        old_ct = ContentType.objects.get(app_label="mozorg", model="person")
        # Get or create the new anonym ContentType
        new_ct, created = ContentType.objects.get_or_create(
            app_label="anonym",
            model="person",
        )

        print("Created new ContentType: anonym.person")

        # Delete the old ContentType
        old_ct.delete()
        print("Deleted old ContentType: mozorg.person")

    except ContentType.DoesNotExist:
        print("ContentType mozorg.person not found, skipping")


def reverse_person_content_type(apps, schema_editor):
    """Reverse the ContentType update (for rollback)."""
    ContentType = apps.get_model("contenttypes", "ContentType")

    try:
        # Get the anonym ContentType
        new_ct = ContentType.objects.get(app_label="anonym", model="person")
        # Recreate the mozorg ContentType
        old_ct, created = ContentType.objects.get_or_create(
            app_label="mozorg",
            model="person",
        )

        # Delete the anonym ContentType
        new_ct.delete()

    except ContentType.DoesNotExist:
        pass


class Migration(migrations.Migration):
    dependencies = [
        ("anonym", "0002_update_anonym_pages_to_new_contenttypes"),
        ("cms", "__latest__"),
        ("contenttypes", "__latest__"),
        ("wagtailcore", "__latest__"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="Person",
                    fields=[
                        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                        ("translation_key", models.UUIDField(editable=False, null=True, verbose_name="translation key")),
                        ("name", models.CharField(max_length=255)),
                        ("position", models.CharField(max_length=255)),
                        ("description", models.TextField(blank=True)),
                        (
                            "image",
                            models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="cms.bedrockimage"),
                        ),
                        (
                            "locale",
                            models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name="+", to="wagtailcore.locale"),
                        ),
                    ],
                    options={
                        "verbose_name": "Person",
                        "verbose_name_plural": "People",
                        "db_table": "mozorg_person",
                        "abstract": False,
                        "unique_together": {("translation_key", "locale")},
                    },
                ),
            ],
            database_operations=[],
        ),
        migrations.RunPython(update_person_content_type, reverse_person_content_type),
    ]
