# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.11 on 2026-02-10 04:10

import wagtail.admin.forms.choosers
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anonym', '0003_alter_anonymcasestudyitempage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonymnewsitempage',
            name='content',
            field=wagtail.fields.StreamField([('intro_text', 1), ('rich_text', 3), ('blockquote', 5), ('figure', 10), ('call_to_action', 26)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'superscript', 'subscript', 'strikethrough']}), 1: ('wagtail.blocks.StructBlock', [[('text', 0)]], {}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'h4', 'h5', 'bold', 'italic', 'ol', 'ul', 'hr', 'link', 'image', 'embed', 'superscript', 'subscript', 'strikethrough', 'blockquote']}), 3: ('wagtail.blocks.StructBlock', [[('text', 2)]], {}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'Author', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('text', 0), ('author', 4)]], {}), 6: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'help_text': 'The Default width is constrained to the layout grid with a max-width, centered on the page.', 'inline_form': True, 'label': 'Make Full Width', 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('make_full_width', 6)]], {}), 8: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 9: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'superscript', 'subscript', 'strikethrough'], 'label': 'Caption', 'required': False}), 10: ('wagtail.blocks.StructBlock', [[('settings', 7), ('image', 8), ('caption', 9)]], {}), 11: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional: Add an ID to make this section linkable from navigation', 'max_length': 100, 'required': False}), 12: ('wagtail.blocks.StructBlock', [[('anchor_id', 11)]], {}), 13: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'superscript', 'subscript', 'strikethrough'], 'help_text': 'Use <strong>bold</strong> to make parts of this text black.'}), 14: ('wagtail.blocks.CharBlock', (), {'label': 'Link Text'}), 15: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('page', 'Page'), ('file', 'File'), ('custom_url', 'Custom URL'), ('email', 'Email'), ('anchor', 'Anchor'), ('phone', 'Phone')], 'classname': 'link_choice_type_selector', 'label': 'Link to', 'required': False}), 16: ('wagtail.blocks.PageChooserBlock', (), {'form_classname': 'page_link', 'label': 'Page', 'required': False}), 17: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'form_classname': 'file_link', 'label': 'File', 'required': False}), 18: ('wagtail.blocks.CharBlock', (), {'form_classname': 'custom_url_link url_field', 'label': 'Custom URL', 'max_length': 300, 'required': False, 'validators': [wagtail.admin.forms.choosers.URLOrAbsolutePathValidator()]}), 19: ('wagtail.blocks.CharBlock', (), {'form_classname': 'anchor_link', 'label': '#', 'max_length': 300, 'required': False}), 20: ('wagtail.blocks.EmailBlock', (), {'required': False}), 21: ('wagtail.blocks.CharBlock', (), {'form_classname': 'phone_link', 'label': 'Phone', 'max_length': 30, 'required': False}), 22: ('wagtail.blocks.BooleanBlock', (), {'form_classname': 'new_window_toggle', 'label': 'Open in new window', 'required': False}), 23: ('wagtail.blocks.StructBlock', [[('link_to', 15), ('page', 16), ('file', 17), ('custom_url', 18), ('anchor', 19), ('email', 20), ('phone', 21), ('new_window', 22)]], {}), 24: ('wagtail.blocks.StructBlock', [[('label', 14), ('link', 23)]], {}), 25: ('wagtail.blocks.ListBlock', (24,), {'default': [], 'max_num': 1, 'min_num': 0}), 26: ('wagtail.blocks.StructBlock', [[('settings', 12), ('heading', 13), ('button', 25)]], {})}, null=True),
        ),
    ]
