# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.9 on 2026-02-10 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("anonym", "0004_alter_anonymnewsitempage_content"),
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="anonymcontactpage",
            name="redirect_to",
            field=models.ForeignKey(
                default=1,
                help_text="Page to redirect to after a successful form submission (e.g. a thank-you page).",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="wagtailcore.page",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="anonymcontactpage",
            name="to_email_address",
            field=models.EmailField(default="sales@anonym.com", help_text="Email address where form submissions will be sent.", max_length=254),
            preserve_default=False,
        ),
    ]
