# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.11 on 2026-03-07 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anonym', '0006_alter_anonymcontentsubpage_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonymcasestudyitempage',
            name='company_name',
            field=models.CharField(blank=True, help_text="Company or client name. This overrides the 'title' field when displayed on the card views.", max_length=255),
        ),
        migrations.AlterField(
            model_name='anonymnewsitempage',
            name='company_name',
            field=models.CharField(blank=True, help_text="Company or client name. This overrides the 'title' field when displayed on the card views.", max_length=255),
        ),
    ]
