# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.9 on 2026-01-21 18:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("anonym", "0007_alter_anonymarticlepage_content_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="anonymcontactpage",
            name="subheading",
            field=models.CharField(blank=True, help_text="Optional subheading for the contact page", max_length=255),
        ),
    ]
