# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.12 on 2026-03-24 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("anonym", "0008_alter_logolistblock_to_streamblock"),
        ("mozorg", "0026_alter_notificationsnippet_notification_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="anonymcontentsubpage",
            name="notification",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="mozorg.notificationsnippet"
            ),
        ),
        migrations.AddField(
            model_name="anonymindexpage",
            name="notification",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="mozorg.notificationsnippet"
            ),
        ),
    ]
