# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.11 on 2026-03-26 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anonym', '0009_anonymcontentsubpage_notification_and_more'),
        ('mozorg', '0026_alter_notificationsnippet_notification_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonymcasestudypage',
            name='notification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='mozorg.notificationsnippet'),
        ),
        migrations.AddField(
            model_name='anonymcontactpage',
            name='notification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='mozorg.notificationsnippet'),
        ),
        migrations.AddField(
            model_name='anonymnewspage',
            name='notification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='mozorg.notificationsnippet'),
        ),
    ]
