# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.9 on 2026-01-21 19:10

from django.db import migrations

import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("anonym", "0009_make_anonymcontactpage_editable"),
    ]

    operations = [
        migrations.AddField(
            model_name="anonymcontactpage",
            name="form_fields",
            field=wagtail.fields.StreamField(
                [("text_field", 4), ("email_field", 4), ("phone_field", 4), ("select_field", 9), ("checkbox_group_field", 10)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Internal name for the field (e.g., 'name', 'email', 'phone_number')", "label": "Internal Identifier"},
                    ),
                    1: ("wagtail.blocks.StructBlock", [[("internal_identifier", 0)]], {}),
                    2: ("wagtail.blocks.CharBlock", (), {"label": "Field Label"}),
                    3: ("wagtail.blocks.BooleanBlock", (), {"default": False, "label": "Required field", "required": False}),
                    4: ("wagtail.blocks.StructBlock", [[("settings", 1), ("label", 2), ("required", 3)]], {}),
                    5: ("wagtail.blocks.CharBlock", (), {"label": "Option Value"}),
                    6: ("wagtail.blocks.CharBlock", (), {"label": "Option Label"}),
                    7: ("wagtail.blocks.StructBlock", [[("value", 5), ("label", 6)]], {}),
                    8: ("wagtail.blocks.ListBlock", (7,), {"label": "Options", "min_num": 1}),
                    9: ("wagtail.blocks.StructBlock", [[("settings", 1), ("label", 2), ("required", 3), ("options", 8)]], {}),
                    10: ("wagtail.blocks.StructBlock", [[("settings", 1), ("label", 2), ("options", 8)]], {}),
                },
                help_text="Define the form fields that will appear on the contact page.",
                null=True,
            ),
        ),
    ]
