# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.9 on 2026-01-22 21:48

from django.db import migrations


def update_contenttype_references(apps, schema_editor):
    """Update page instances to use the new ContentType."""
    ContentType = apps.get_model("contenttypes", "ContentType")
    Page = apps.get_model("wagtailcore", "Page")

    # Get the old and new ContentTypes
    try:
        old_ct = ContentType.objects.get(app_label="anonym", model="anonymarticlepage")
    except ContentType.DoesNotExist:
        # Old ContentType already deleted, nothing to do
        return

    try:
        new_ct = ContentType.objects.get(app_label="anonym", model="anonymcasestudyitempage")
    except ContentType.DoesNotExist:
        # New ContentType doesn't exist, which shouldn't happen
        return

    # Update all pages using the old ContentType to use the new one
    Page.objects.filter(content_type=old_ct).update(content_type=new_ct)

    # Delete the old ContentType
    old_ct.delete()


def reverse_update_contenttype(apps, schema_editor):
    """Reverse is not supported."""
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("anonym", "0011_alter_anonymarticlepage_content_and_more"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("mozorg", "0034_remove_person"),
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AnonymArticlePage",
            new_name="AnonymCaseStudyItemPage",
        ),
        migrations.AlterModelOptions(
            name="anonymcasestudyitempage",
            options={"verbose_name": "Anonym Case Study Item Page"},
        ),
        migrations.RunPython(update_contenttype_references, reverse_update_contenttype),
    ]
