# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.12 on 2026-04-16 19:34

from django.db import migrations

import wagtail.admin.forms.choosers
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("anonym", "0013_alter_anonymcasestudyitempage_content_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="anonymindexpage",
            name="navigation",
            field=wagtail.fields.StreamField(
                [("link", 12)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"help_text": "Text to display for this navigation link", "max_length": 50}),
                    1: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("page", "Page"),
                                ("file", "File"),
                                ("custom_url", "Custom URL"),
                                ("email", "Email"),
                                ("anchor", "Anchor"),
                                ("phone", "Phone"),
                            ],
                            "classname": "link_choice_type_selector",
                            "label": "Link to",
                            "required": False,
                        },
                    ),
                    2: ("wagtail.blocks.PageChooserBlock", (), {"form_classname": "page_link", "label": "Page", "required": False}),
                    3: ("wagtail.documents.blocks.DocumentChooserBlock", (), {"form_classname": "file_link", "label": "File", "required": False}),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "form_classname": "custom_url_link url_field",
                            "label": "Custom URL",
                            "max_length": 300,
                            "required": False,
                            "validators": [wagtail.admin.forms.choosers.URLOrAbsolutePathValidator()],
                        },
                    ),
                    5: ("wagtail.blocks.CharBlock", (), {"form_classname": "anchor_link", "label": "#", "max_length": 300, "required": False}),
                    6: ("wagtail.blocks.EmailBlock", (), {"required": False}),
                    7: ("wagtail.blocks.CharBlock", (), {"form_classname": "phone_link", "label": "Phone", "max_length": 30, "required": False}),
                    8: ("wagtail.blocks.BooleanBlock", (), {"form_classname": "new_window_toggle", "label": "Open in new window", "required": False}),
                    9: (
                        "wagtail.blocks.StructBlock",
                        [[("link_to", 1), ("page", 2), ("file", 3), ("custom_url", 4), ("anchor", 5), ("email", 6), ("phone", 7), ("new_window", 8)]],
                        {},
                    ),
                    10: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"default": False, "help_text": "This link should look like a button", "required": False},
                    ),
                    11: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Unique identifier for analytics tracking. Leave blank for standard nav links.",
                            "label": "Analytics ID",
                            "required": False,
                        },
                    ),
                    12: ("wagtail.blocks.StructBlock", [[("link_text", 0), ("link", 9), ("has_button_appearance", 10), ("analytics_id", 11)]], {}),
                },
                help_text="Configure the navigation menu items.",
                null=True,
            ),
        ),
    ]
