# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.12 on 2026-04-16 19:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("anonym", "0014_alter_anonymindexpage_navigation"),
    ]

    operations = [
        migrations.AddField(
            model_name="anonymnewsitempage",
            name="analytics_id",
            field=models.CharField(blank=True, help_text="Unique identifier for analytics tracking. Leave blank to auto-generate.", max_length=36),
        ),
    ]
