# Generated by Django 5.2.9 on 2026-01-23 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("anonym", "0014_alter_anonymcasestudyitempage_content_and_more"),
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnonymCaseStudyPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
            ],
            options={
                "verbose_name": "Anonym Case Study Page",
                "verbose_name_plural": "Anonym Case Study Pages",
            },
            bases=("wagtailcore.page",),
        ),
    ]
