# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.9 on 2026-01-30 02:52

from django.db import migrations

import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("anonym", "0017_alter_anonymcasestudyitempage_content_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="anonymnewsitempage",
            name="stats",
            field=wagtail.fields.StreamField(
                [("stat", 2)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"features": ["bold", "italic", "link", "superscript", "subscript", "strikethrough"], "label": "Statistic Value"},
                    ),
                    1: ("wagtail.blocks.CharBlock", (), {"label": "Statistic Label"}),
                    2: ("wagtail.blocks.StructBlock", [[("statistic_value", 0), ("statistic_label", 1)]], {}),
                },
                help_text="Statistics that will display if this news item is shown on the homepage",
                null=True,
            ),
        ),
    ]
