# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.9 on 2026-02-05 20:41

import django.db.models.deletion
from django.db import migrations, models

import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("anonym", "0022_rename_newsitemlistblock_to_statitemlistblock"),
        ("cms", "0004_bedrocklocale"),
    ]

    operations = [
        migrations.RenameField(
            model_name="anonymcasestudyitempage",
            old_name="client",
            new_name="company_name",
        ),
        migrations.AlterField(
            model_name="anonymcasestudyitempage",
            name="company_name",
            field=models.CharField(blank=True, help_text="Company or client name", max_length=255),
        ),
        migrations.RenameField(
            model_name="anonymnewsitempage",
            old_name="description",
            new_name="company_name",
        ),
        migrations.AddField(
            model_name="anonymcasestudyitempage",
            name="link",
            field=models.URLField(blank=True, help_text="External link"),
        ),
        migrations.AddField(
            model_name="anonymcasestudyitempage",
            name="stats",
            field=wagtail.fields.StreamField(
                [("stat", 2)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"features": ["bold", "italic", "link", "superscript", "subscript", "strikethrough"], "label": "Statistic Value"},
                    ),
                    1: ("wagtail.blocks.CharBlock", (), {"label": "Statistic Label"}),
                    2: ("wagtail.blocks.StructBlock", [[("statistic_value", 0), ("statistic_label", 1)]], {}),
                },
                help_text="Statistics to display",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="anonymnewsitempage",
            name="company_name",
            field=models.CharField(blank=True, help_text="Company or client name", max_length=255),
        ),
        migrations.AlterField(
            model_name="anonymcasestudyitempage",
            name="logo",
            field=models.ForeignKey(
                blank=True, help_text="Logo image", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="cms.bedrockimage"
            ),
        ),
        migrations.AlterField(
            model_name="anonymnewsitempage",
            name="link",
            field=models.URLField(blank=True, help_text="External link"),
        ),
        migrations.AlterField(
            model_name="anonymnewsitempage",
            name="logo",
            field=models.ForeignKey(
                blank=True, help_text="Logo image", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="cms.bedrockimage"
            ),
        ),
        migrations.AlterField(
            model_name="anonymnewsitempage",
            name="stats",
            field=wagtail.fields.StreamField(
                [("stat", 2)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"features": ["bold", "italic", "link", "superscript", "subscript", "strikethrough"], "label": "Statistic Value"},
                    ),
                    1: ("wagtail.blocks.CharBlock", (), {"label": "Statistic Label"}),
                    2: ("wagtail.blocks.StructBlock", [[("statistic_value", 0), ("statistic_label", 1)]], {}),
                },
                help_text="Statistics to display",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="anonymnewsitempage",
            name="description",
            field=models.TextField(blank=True, help_text="Description of the news item"),
        ),
    ]
