# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.9 on 2026-02-05 21:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("anonym", "0025_newsitempages_and_casestudypages_logolistblock"),
    ]

    operations = [
        migrations.AddField(
            model_name="anonymnewsitempage",
            name="is_featured",
            field=models.BooleanField(default=False, help_text="Feature this news item at the top of the news page"),
        ),
    ]
