# Generated by Django 2.2.8 on 2020-01-22 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20150612_0919'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
