DOCKER_REPOSITORY=${DOCKER_REPOSITORY:-mozorg/mcom-tests}

SAUCE_CREDENTIALS_PATH=`mktemp`
cat << EOF > $SAUCE_CREDENTIALS_PATH
username: $SAUCELABS_USERNAME
password: $SAUCELABS_PASSWORD
api-key: $SAUCELABS_API_KEY
EOF

docker pull ${DOCKER_REPOSITORY}
docker run -v $SAUCE_CREDENTIALS_PATH:/tmp/creds -v `pwd`/results/:/app/results -e BASE_URL=${BASE_URL} -e BUILD_TAG=${BUILD_TAG} ${DOCKER_REPOSITORY}
