# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 2.2.26 on 2022-01-19 00:14

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = []
