# Generated by Django 2.2.8 on 2020-01-22 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mozorg', '0003_delete_blogarticle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContributorActivity',
        ),
        migrations.DeleteModel(
            name='TwitterCache',
        ),
    ]
