# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.1.8 on 2025-04-14 09:52

from django.db import migrations

import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("mozorg", "0005_alter_leadershippage_leadership_sections"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leadershippage",
            name="leadership_sections",
            field=wagtail.fields.StreamField(
                [("section", 18)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "blank": True,
                            "help_text": "Title for the section of the page e.g. 'Mozilla Corporation' or 'Mozilla Foundation.",
                            "max_length": 255,
                            "null": True,
                        },
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "char_max_length": 255,
                            "help_text": "Leadership group title, e.g. 'Executive Steering Committee' or 'Senior Leadership'.",
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "char_max_length": 255,
                            "placeholder": "Enter the person's full name.",
                        },
                    ),
                    3: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"help_text": "A headshot image of the person."},
                    ),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "char_max_length": 255,
                            "help_text": "Alt text for the headshot image.",
                        },
                    ),
                    5: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "char_max_length": 255,
                            "help_text": "External link to a .zip file of photos of the person.",
                            "required": False,
                        },
                    ),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 3), ("image_alt_text", 4), ("photos_link", 5)]],
                        {},
                    ),
                    7: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"char_max_length": 255, "required": False},
                    ),
                    8: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "h2",
                                "h3",
                                "hr",
                                "bold",
                                "italic",
                                "code",
                                "blockquote",
                                "superscript",
                                "link",
                                "ol",
                                "ul",
                                "image",
                            ],
                            "help_text": "A biography limited to a few short paragraphs. Links and formatting are supported.",
                            "required": False,
                        },
                    ),
                    9: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "char_max_length": 255,
                            "help_text": "Link to the person's website or social media account.",
                            "required": False,
                        },
                    ),
                    10: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("url mastodon", "Mastodon"),
                                ("url twitter", "Twitter"),
                                ("url website", "Website"),
                            ],
                            "help_text": "Selects a visual icon type for the link.",
                            "required": False,
                        },
                    ),
                    11: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "char_max_length": 255,
                            "help_text": "Text to display for the link.",
                            "required": False,
                        },
                    ),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [[("url", 9), ("type", 10), ("text", 11)]],
                        {},
                    ),
                    13: (
                        "wagtail.blocks.ListBlock",
                        (12,),
                        {"max_num": 5, "min_num": 0},
                    ),
                    14: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("name", 2),
                                ("headshot", 6),
                                ("job_title", 7),
                                ("biography", 8),
                                ("external_links", 13),
                            ]
                        ],
                        {},
                    ),
                    15: ("wagtail.blocks.ListBlock", (14,), {"min_num": 1}),
                    16: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 1), ("leaders", 15)]],
                        {},
                    ),
                    17: ("wagtail.blocks.ListBlock", (16,), {"min_num": 1}),
                    18: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("leadership_group", 17)]],
                        {},
                    ),
                },
                null=True,
            ),
        ),
    ]
