# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.8 on 2025-11-14 18:15

from django.db import migrations

import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("mozorg", "0006_alter_leadershippage_leadership_sections"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leadershippage",
            name="leadership_sections",
            field=wagtail.fields.StreamField(
                [("section", 20)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "blank": True,
                            "help_text": "Title for the section of the page e.g. 'Mozilla Corporation' or 'Mozilla Foundation.",
                            "max_length": 255,
                            "null": True,
                        },
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"char_max_length": 255, "help_text": "Description for the leadership section.", "required": False},
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "char_max_length": 255,
                            "help_text": "Leadership group title, e.g. 'Executive Steering Committee' or 'Senior Leadership'.",
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "char_max_length": 255,
                            "help_text": "A couple of sentences describes what the group is and some helpful context.",
                            "required": False,
                        },
                    ),
                    4: ("wagtail.blocks.CharBlock", (), {"char_max_length": 255, "placeholder": "Enter the person's full name."}),
                    5: ("wagtail.images.blocks.ImageChooserBlock", (), {"help_text": "A headshot image of the person."}),
                    6: ("wagtail.blocks.CharBlock", (), {"char_max_length": 255, "help_text": "Alt text for the headshot image."}),
                    7: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"char_max_length": 255, "help_text": "External link to a .zip file of photos of the person.", "required": False},
                    ),
                    8: ("wagtail.blocks.StructBlock", [[("image", 5), ("image_alt_text", 6), ("photos_link", 7)]], {}),
                    9: ("wagtail.blocks.CharBlock", (), {"char_max_length": 255, "required": False}),
                    10: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["h2", "h3", "hr", "bold", "italic", "code", "blockquote", "superscript", "link", "ol", "ul", "image"],
                            "help_text": "A biography limited to a few short paragraphs. Links and formatting are supported.",
                            "required": False,
                        },
                    ),
                    11: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"char_max_length": 255, "help_text": "Link to the person's website or social media account.", "required": False},
                    ),
                    12: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("url mastodon", "Mastodon"), ("url twitter", "Twitter"), ("url website", "Website")],
                            "help_text": "Selects a visual icon type for the link.",
                            "required": False,
                        },
                    ),
                    13: ("wagtail.blocks.CharBlock", (), {"char_max_length": 255, "help_text": "Text to display for the link.", "required": False}),
                    14: ("wagtail.blocks.StructBlock", [[("url", 11), ("type", 12), ("text", 13)]], {}),
                    15: ("wagtail.blocks.ListBlock", (14,), {"max_num": 5, "min_num": 0}),
                    16: (
                        "wagtail.blocks.StructBlock",
                        [[("name", 4), ("headshot", 8), ("job_title", 9), ("biography", 10), ("external_links", 15)]],
                        {},
                    ),
                    17: ("wagtail.blocks.ListBlock", (16,), {"min_num": 1}),
                    18: ("wagtail.blocks.StructBlock", [[("title", 2), ("description", 3), ("leaders", 17)]], {}),
                    19: ("wagtail.blocks.ListBlock", (18,), {"min_num": 1}),
                    20: ("wagtail.blocks.StructBlock", [[("title", 0), ("description", 1), ("leadership_group", 19)]], {}),
                },
                null=True,
            ),
        ),
    ]
