# Generated by Django 5.2.7 on 2025-10-15 13:37

import django.db.models.deletion
from django.db import migrations, models

import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("mozorg", "0006_alter_leadershippage_leadership_sections"),
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdvertisingIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "content",
                    wagtail.fields.StreamField(
                        [("advertising_hero_block", 4), ("section_header_block", 7), ("figure_with_statistic_block", 10)],
                        blank=True,
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {"char_max_length": 255}),
                            1: ("wagtail.blocks.URLBlock", (), {"char_max_length": 255, "help_text": "Link URL for the primary CTA."}),
                            2: ("wagtail.blocks.TextBlock", (), {}),
                            3: ("wagtail.blocks.URLBlock", (), {"char_max_length": 255, "help_text": "Link URL for the secondary CTA."}),
                            4: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("heading_text", 0),
                                        ("primary_cta_text", 0),
                                        ("primary_cta_link", 1),
                                        ("supporting_text", 2),
                                        ("secondary_cta_text", 0),
                                        ("secondary_cta_link", 3),
                                    ]
                                ],
                                {},
                            ),
                            5: ("wagtail.blocks.CharBlock", (), {"char_max_length": 255, "required": False}),
                            6: ("wagtail.images.blocks.ImageChooserBlock", (), {"required": False}),
                            7: (
                                "wagtail.blocks.StructBlock",
                                [[("superheading_text", 5), ("heading_text", 0), ("subheading_text", 5), ("image", 6), ("image_alt_text", 5)]],
                                {},
                            ),
                            8: ("wagtail.blocks.RichTextBlock", (), {"char_max_length": 255}),
                            9: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {
                                    "default": False,
                                    "inline_form": True,
                                    "label": "Should the image be to the right of the statistic?",
                                    "required": False,
                                },
                            ),
                            10: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("image", 6),
                                        ("image_alt_text", 0),
                                        ("image_caption", 8),
                                        ("statistic_value", 0),
                                        ("statistic_label", 0),
                                        ("align_image_on_right", 9),
                                    ]
                                ],
                                {},
                            ),
                        },
                        null=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
