# Generated by Django 5.2.7 on 2025-10-16 21:03

import django.db.models.deletion
from django.db import migrations, models

import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("mozorg", "0008_contactbannersnippet_and_more"),
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.CreateModel(
            name="TwoColumnSubpage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("heading", models.CharField(blank=True, max_length=255)),
                ("subheading", models.CharField(blank=True, max_length=255)),
                (
                    "second_column",
                    wagtail.fields.StreamField(
                        [("list_item", 2)],
                        blank=True,
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {"char_max_length": 255}),
                            1: ("wagtail.blocks.RichTextBlock", (), {"features": ["bold", "italic", "link"]}),
                            2: ("wagtail.blocks.StructBlock", [[("heading_text", 0), ("supporting_text", 1)]], {}),
                        },
                        null=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
