# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.8 on 2025-11-24 17:26

from django.db import migrations

import wagtail.admin.forms.choosers
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("mozorg", "0008_contactbannersnippet_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advertisingindexpage",
            name="content",
            field=wagtail.fields.StreamField(
                [("advertising_hero_block", 12), ("section_header_block", 16), ("figure_with_statistic_block", 20), ("feature_list_block", 23)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"char_max_length": 255}),
                    1: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("page", "Page"),
                                ("file", "File"),
                                ("custom_url", "Custom URL"),
                                ("email", "Email"),
                                ("anchor", "Anchor"),
                                ("phone", "Phone"),
                            ],
                            "classname": "link_choice_type_selector",
                            "label": "Link to",
                            "required": False,
                        },
                    ),
                    2: ("wagtail.blocks.PageChooserBlock", (), {"form_classname": "page_link", "label": "Page", "required": False}),
                    3: ("wagtail.documents.blocks.DocumentChooserBlock", (), {"form_classname": "file_link", "label": "File", "required": False}),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "form_classname": "custom_url_link url_field",
                            "label": "Custom URL",
                            "max_length": 300,
                            "required": False,
                            "validators": [wagtail.admin.forms.choosers.URLOrAbsolutePathValidator()],
                        },
                    ),
                    5: ("wagtail.blocks.CharBlock", (), {"form_classname": "anchor_link", "label": "#", "max_length": 300, "required": False}),
                    6: ("wagtail.blocks.EmailBlock", (), {"required": False}),
                    7: ("wagtail.blocks.CharBlock", (), {"form_classname": "phone_link", "label": "Phone", "max_length": 30, "required": False}),
                    8: ("wagtail.blocks.BooleanBlock", (), {"form_classname": "new_window_toggle", "label": "Open in new window", "required": False}),
                    9: (
                        "wagtail.blocks.StructBlock",
                        [[("link_to", 1), ("page", 2), ("file", 3), ("custom_url", 4), ("anchor", 5), ("email", 6), ("phone", 7), ("new_window", 8)]],
                        {"label": "Primary CTA Link"},
                    ),
                    10: ("wagtail.blocks.TextBlock", (), {}),
                    11: (
                        "wagtail.blocks.StructBlock",
                        [[("link_to", 1), ("page", 2), ("file", 3), ("custom_url", 4), ("anchor", 5), ("email", 6), ("phone", 7), ("new_window", 8)]],
                        {"label": "Secondary CTA Link"},
                    ),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading_text", 0),
                                ("primary_cta_text", 0),
                                ("primary_cta_link", 9),
                                ("supporting_text", 10),
                                ("secondary_cta_text", 0),
                                ("secondary_cta_link", 11),
                            ]
                        ],
                        {},
                    ),
                    13: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"default": False, "inline_form": True, "label": "Should the section have a divider line on top?", "required": False},
                    ),
                    14: ("wagtail.blocks.CharBlock", (), {"char_max_length": 255, "required": False}),
                    15: ("wagtail.images.blocks.ImageChooserBlock", (), {"required": False}),
                    16: (
                        "wagtail.blocks.StructBlock",
                        [[("has_top_divider", 13), ("superheading_text", 14), ("heading_text", 0), ("subheading_text", 14), ("image", 15)]],
                        {},
                    ),
                    17: ("wagtail.blocks.RichTextBlock", (), {"char_max_length": 255}),
                    18: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"default": False, "inline_form": True, "label": "Position the image to the right of the statistic", "required": False},
                    ),
                    19: (
                        "wagtail.blocks.StructBlock",
                        [[("link_to", 1), ("page", 2), ("file", 3), ("custom_url", 4), ("anchor", 5), ("email", 6), ("phone", 7), ("new_window", 8)]],
                        {"label": "Link", "required": False},
                    ),
                    20: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image", 15),
                                ("image_caption", 17),
                                ("statistic_value", 0),
                                ("statistic_label", 0),
                                ("align_image_on_right", 18),
                                ("cta_text", 14),
                                ("cta_link", 19),
                            ]
                        ],
                        {},
                    ),
                    21: ("wagtail.blocks.StructBlock", [[("heading_text", 0), ("supporting_text", 10)]], {}),
                    22: ("wagtail.blocks.ListBlock", (21,), {"min_num": 1}),
                    23: ("wagtail.blocks.StructBlock", [[("feature_list_items", 22)]], {}),
                },
                null=True,
            ),
        ),
    ]
