# Generated by Django 5.2.7 on 2025-10-16 18:43

from django.db import migrations

import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("mozorg", "0009_advertisingprinciplespage"),
    ]

    operations = [
        migrations.AddField(
            model_name="advertisingindexpage",
            name="sub_navigation",
            field=wagtail.fields.StreamField(
                [("link", 6)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"help_text": "Text to display for this navigation link", "max_length": 50}),
                    1: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("section", "Link to Section on this Page"), ("page", "Internal Page"), ("external", "External URL")],
                            "help_text": "Choose the type of link",
                        },
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Enter the Anchor ID from one of the content sections below. Available anchors will be shown when you save.",
                            "max_length": 100,
                            "required": False,
                        },
                    ),
                    3: ("wagtail.blocks.PageChooserBlock", (), {"help_text": "Choose an internal page to link to", "required": False}),
                    4: ("wagtail.blocks.URLBlock", (), {"help_text": "Full URL for external links", "max_length": 255, "required": False}),
                    5: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Optional CSS class (e.g., 'mozads-c-contact-sales-button')", "max_length": 100, "required": False},
                    ),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [[("link_text", 0), ("link_type", 1), ("section_anchor", 2), ("internal_page", 3), ("external_url", 4), ("style_class", 5)]],
                        {},
                    ),
                },
                help_text="Configure the sub-navigation menu items. Leave empty to use the default navigation.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="advertisingindexpage",
            name="content",
            field=wagtail.fields.StreamField(
                [("advertising_hero_block", 5), ("section_header_block", 9), ("figure_with_statistic_block", 13), ("feature_list_block", 16)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional: Add an ID to make this section linkable from navigation (e.g., 'hero', 'overview')",
                            "max_length": 100,
                            "required": False,
                        },
                    ),
                    1: ("wagtail.blocks.CharBlock", (), {"char_max_length": 255}),
                    2: ("wagtail.blocks.URLBlock", (), {"char_max_length": 255, "help_text": "Link URL for the primary CTA."}),
                    3: ("wagtail.blocks.TextBlock", (), {}),
                    4: ("wagtail.blocks.URLBlock", (), {"char_max_length": 255, "help_text": "Link URL for the secondary CTA."}),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("anchor_id", 0),
                                ("heading_text", 1),
                                ("primary_cta_text", 1),
                                ("primary_cta_link", 2),
                                ("supporting_text", 3),
                                ("secondary_cta_text", 1),
                                ("secondary_cta_link", 4),
                            ]
                        ],
                        {},
                    ),
                    6: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional: Add an ID to make this section linkable from navigation (e.g., 'solutions', 'why-mozilla')",
                            "max_length": 100,
                            "required": False,
                        },
                    ),
                    7: ("wagtail.blocks.CharBlock", (), {"char_max_length": 255, "required": False}),
                    8: ("wagtail.images.blocks.ImageChooserBlock", (), {"required": False}),
                    9: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("anchor_id", 6),
                                ("superheading_text", 7),
                                ("heading_text", 1),
                                ("subheading_text", 7),
                                ("image", 8),
                                ("image_alt_text", 7),
                            ]
                        ],
                        {},
                    ),
                    10: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Optional: Add an ID to make this section linkable from navigation", "max_length": 100, "required": False},
                    ),
                    11: ("wagtail.blocks.RichTextBlock", (), {"char_max_length": 255}),
                    12: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"default": False, "inline_form": True, "label": "Should the image be to the right of the statistic?", "required": False},
                    ),
                    13: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("anchor_id", 10),
                                ("image", 8),
                                ("image_alt_text", 1),
                                ("image_caption", 11),
                                ("statistic_value", 1),
                                ("statistic_label", 1),
                                ("align_image_on_right", 12),
                            ]
                        ],
                        {},
                    ),
                    14: ("wagtail.blocks.StructBlock", [[("heading_text", 1), ("supporting_text", 3)]], {}),
                    15: ("wagtail.blocks.ListBlock", (14,), {"min_num": 1}),
                    16: ("wagtail.blocks.StructBlock", [[("anchor_id", 10), ("feature_list_items", 15)]], {}),
                },
                null=True,
            ),
        ),
    ]
