# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.8 on 2025-11-24 17:27

from django.db import migrations

import wagtail.admin.forms.choosers
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("mozorg", "0009_alter_advertisingindexpage_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advertisingindexpage",
            name="notifications",
            field=wagtail.fields.StreamField(
                [("notification_block", 13)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"char_max_length": 255, "features": ["bold", "italic", "superscript", "subscript", "strikethrough", "code", "link"]},
                    ),
                    1: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("linkedin", "LinkedIn"),
                                ("tiktok", "TikTok"),
                                ("spotify", "Spotify"),
                                ("bluesky", "BlueSky"),
                                ("instagram", "Instagram"),
                                ("youtube", "YouTube"),
                            ],
                            "inline_form": True,
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("page", "Page"),
                                ("file", "File"),
                                ("custom_url", "Custom URL"),
                                ("email", "Email"),
                                ("anchor", "Anchor"),
                                ("phone", "Phone"),
                            ],
                            "classname": "link_choice_type_selector",
                            "label": "Link to",
                            "required": False,
                        },
                    ),
                    3: ("wagtail.blocks.PageChooserBlock", (), {"form_classname": "page_link", "label": "Page", "required": False}),
                    4: ("wagtail.documents.blocks.DocumentChooserBlock", (), {"form_classname": "file_link", "label": "File", "required": False}),
                    5: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "form_classname": "custom_url_link url_field",
                            "label": "Custom URL",
                            "max_length": 300,
                            "required": False,
                            "validators": [wagtail.admin.forms.choosers.URLOrAbsolutePathValidator()],
                        },
                    ),
                    6: ("wagtail.blocks.CharBlock", (), {"form_classname": "anchor_link", "label": "#", "max_length": 300, "required": False}),
                    7: ("wagtail.blocks.EmailBlock", (), {"required": False}),
                    8: ("wagtail.blocks.CharBlock", (), {"form_classname": "phone_link", "label": "Phone", "max_length": 30, "required": False}),
                    9: ("wagtail.blocks.BooleanBlock", (), {"form_classname": "new_window_toggle", "label": "Open in new window", "required": False}),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [[("link_to", 2), ("page", 3), ("file", 4), ("custom_url", 5), ("anchor", 6), ("email", 7), ("phone", 8), ("new_window", 9)]],
                        {},
                    ),
                    11: ("wagtail.blocks.StructBlock", [[("icon", 1), ("link", 10)]], {}),
                    12: ("wagtail.blocks.StreamBlock", [[("link_with_icon", 11)]], {"required": False}),
                    13: ("wagtail.blocks.StructBlock", [[("notification_text", 0), ("links", 12)]], {}),
                },
                null=True,
            ),
        ),
    ]
