# Generated by Django 5.2.8 on 2025-11-24 17:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mozorg", "0011_advertisingprinciplespage"),
        ("wagtailcore", "0095_groupsitepermission"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TwoColumnSubpage",
            new_name="AdvertisingTwoColumnSubpage",
        ),
    ]
