# Generated by Django 5.2.7 on 2025-10-31 19:08

from django.db import migrations

import wagtail.admin.forms.choosers
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("mozorg", "0011_contentsubpage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advertisingindexpage",
            name="content",
            field=wagtail.fields.StreamField(
                [("advertising_hero_block", 13), ("section_header_block", 19), ("figure_with_statistic_block", 24), ("feature_list_block", 27)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional: Add an ID to make this section linkable from navigation (e.g., 'hero', 'overview')",
                            "max_length": 100,
                            "required": False,
                        },
                    ),
                    1: ("wagtail.blocks.CharBlock", (), {"char_max_length": 255}),
                    2: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("page", "Page"),
                                ("file", "File"),
                                ("custom_url", "Custom URL"),
                                ("email", "Email"),
                                ("anchor", "Anchor"),
                                ("phone", "Phone"),
                            ],
                            "classname": "link_choice_type_selector",
                            "label": "Link to",
                            "required": False,
                        },
                    ),
                    3: ("wagtail.blocks.PageChooserBlock", (), {"form_classname": "page_link", "label": "Page", "required": False}),
                    4: ("wagtail.documents.blocks.DocumentChooserBlock", (), {"form_classname": "file_link", "label": "File", "required": False}),
                    5: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "form_classname": "custom_url_link url_field",
                            "label": "Custom URL",
                            "max_length": 300,
                            "required": False,
                            "validators": [wagtail.admin.forms.choosers.URLOrAbsolutePathValidator()],
                        },
                    ),
                    6: ("wagtail.blocks.CharBlock", (), {"form_classname": "anchor_link", "label": "#", "max_length": 300, "required": False}),
                    7: ("wagtail.blocks.EmailBlock", (), {"required": False}),
                    8: ("wagtail.blocks.CharBlock", (), {"form_classname": "phone_link", "label": "Phone", "max_length": 30, "required": False}),
                    9: ("wagtail.blocks.BooleanBlock", (), {"form_classname": "new_window_toggle", "label": "Open in new window", "required": False}),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [[("link_to", 2), ("page", 3), ("file", 4), ("custom_url", 5), ("anchor", 6), ("email", 7), ("phone", 8), ("new_window", 9)]],
                        {"label": "Primary CTA Link"},
                    ),
                    11: ("wagtail.blocks.TextBlock", (), {}),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [[("link_to", 2), ("page", 3), ("file", 4), ("custom_url", 5), ("anchor", 6), ("email", 7), ("phone", 8), ("new_window", 9)]],
                        {"label": "Secondary CTA Link"},
                    ),
                    13: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("anchor_id", 0),
                                ("heading_text", 1),
                                ("primary_cta_text", 1),
                                ("primary_cta_link", 10),
                                ("supporting_text", 11),
                                ("secondary_cta_text", 1),
                                ("secondary_cta_link", 12),
                            ]
                        ],
                        {},
                    ),
                    14: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional: Add an ID to make this section linkable from navigation (e.g., 'solutions', 'why-mozilla')",
                            "max_length": 100,
                            "required": False,
                        },
                    ),
                    15: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"default": False, "inline_form": True, "label": "Should the section have a divider line on top?", "required": False},
                    ),
                    16: ("wagtail.blocks.CharBlock", (), {"char_max_length": 255, "required": False}),
                    17: ("wagtail.images.blocks.ImageChooserBlock", (), {"required": False}),
                    18: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "inline_form": True,
                            "label": "Should the section colors match the colors of the header?",
                            "required": False,
                        },
                    ),
                    19: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("anchor_id", 14),
                                ("has_top_divider", 15),
                                ("superheading_text", 16),
                                ("heading_text", 1),
                                ("subheading_text", 16),
                                ("image", 17),
                                ("colors_should_match_header", 18),
                            ]
                        ],
                        {},
                    ),
                    20: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Optional: Add an ID to make this section linkable from navigation", "max_length": 100, "required": False},
                    ),
                    21: ("wagtail.blocks.RichTextBlock", (), {"char_max_length": 255, "required": False}),
                    22: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"default": False, "inline_form": True, "label": "Should the image be to the right of the statistic?", "required": False},
                    ),
                    23: (
                        "wagtail.blocks.StructBlock",
                        [[("link_to", 2), ("page", 3), ("file", 4), ("custom_url", 5), ("anchor", 6), ("email", 7), ("phone", 8), ("new_window", 9)]],
                        {"label": "Link", "required": False},
                    ),
                    24: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("anchor_id", 20),
                                ("image", 17),
                                ("image_caption", 21),
                                ("statistic_value", 1),
                                ("statistic_label", 1),
                                ("align_image_on_right", 22),
                                ("cta_text", 16),
                                ("cta_link", 23),
                                ("colors_should_match_header", 18),
                            ]
                        ],
                        {},
                    ),
                    25: ("wagtail.blocks.StructBlock", [[("heading_text", 1), ("supporting_text", 11)]], {}),
                    26: ("wagtail.blocks.ListBlock", (25,), {"min_num": 1}),
                    27: ("wagtail.blocks.StructBlock", [[("anchor_id", 20), ("feature_list_items", 26)]], {}),
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="contentsubpage",
            name="content",
            field=wagtail.fields.StreamField(
                [("section_header_block", 6), ("figure_with_statistic_block", 19)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional: Add an ID to make this section linkable from navigation (e.g., 'solutions', 'why-mozilla')",
                            "max_length": 100,
                            "required": False,
                        },
                    ),
                    1: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"default": False, "inline_form": True, "label": "Should the section have a divider line on top?", "required": False},
                    ),
                    2: ("wagtail.blocks.CharBlock", (), {"char_max_length": 255, "required": False}),
                    3: ("wagtail.blocks.CharBlock", (), {"char_max_length": 255}),
                    4: ("wagtail.images.blocks.ImageChooserBlock", (), {"required": False}),
                    5: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "inline_form": True,
                            "label": "Should the section colors match the colors of the header?",
                            "required": False,
                        },
                    ),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("anchor_id", 0),
                                ("has_top_divider", 1),
                                ("superheading_text", 2),
                                ("heading_text", 3),
                                ("subheading_text", 2),
                                ("image", 4),
                                ("colors_should_match_header", 5),
                            ]
                        ],
                        {},
                    ),
                    7: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Optional: Add an ID to make this section linkable from navigation", "max_length": 100, "required": False},
                    ),
                    8: ("wagtail.blocks.RichTextBlock", (), {"char_max_length": 255, "required": False}),
                    9: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"default": False, "inline_form": True, "label": "Should the image be to the right of the statistic?", "required": False},
                    ),
                    10: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("page", "Page"),
                                ("file", "File"),
                                ("custom_url", "Custom URL"),
                                ("email", "Email"),
                                ("anchor", "Anchor"),
                                ("phone", "Phone"),
                            ],
                            "classname": "link_choice_type_selector",
                            "label": "Link to",
                            "required": False,
                        },
                    ),
                    11: ("wagtail.blocks.PageChooserBlock", (), {"form_classname": "page_link", "label": "Page", "required": False}),
                    12: ("wagtail.documents.blocks.DocumentChooserBlock", (), {"form_classname": "file_link", "label": "File", "required": False}),
                    13: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "form_classname": "custom_url_link url_field",
                            "label": "Custom URL",
                            "max_length": 300,
                            "required": False,
                            "validators": [wagtail.admin.forms.choosers.URLOrAbsolutePathValidator()],
                        },
                    ),
                    14: ("wagtail.blocks.CharBlock", (), {"form_classname": "anchor_link", "label": "#", "max_length": 300, "required": False}),
                    15: ("wagtail.blocks.EmailBlock", (), {"required": False}),
                    16: ("wagtail.blocks.CharBlock", (), {"form_classname": "phone_link", "label": "Phone", "max_length": 30, "required": False}),
                    17: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"form_classname": "new_window_toggle", "label": "Open in new window", "required": False},
                    ),
                    18: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("link_to", 10),
                                ("page", 11),
                                ("file", 12),
                                ("custom_url", 13),
                                ("anchor", 14),
                                ("email", 15),
                                ("phone", 16),
                                ("new_window", 17),
                            ]
                        ],
                        {"label": "Link", "required": False},
                    ),
                    19: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("anchor_id", 7),
                                ("image", 4),
                                ("image_caption", 8),
                                ("statistic_value", 3),
                                ("statistic_label", 3),
                                ("align_image_on_right", 9),
                                ("cta_text", 2),
                                ("cta_link", 18),
                                ("colors_should_match_header", 5),
                            ]
                        ],
                        {},
                    ),
                },
                null=True,
            ),
        ),
    ]
