# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.7 on 2025-10-16 18:43

from django.db import migrations

import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("mozorg", "0012_rename_twocolumnsubpage_advertisingtwocolumnsubpage"),
    ]

    operations = [
        migrations.AddField(
            model_name="advertisingindexpage",
            name="sub_navigation",
            field=wagtail.fields.StreamField(
                [("link", 11)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"help_text": "Text to display for this navigation link", "max_length": 50}),
                    1: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("page", "Page"),
                                ("file", "File"),
                                ("custom_url", "Custom URL"),
                                ("email", "Email"),
                                ("anchor", "Anchor"),
                                ("phone", "Phone"),
                            ],
                            "classname": "link_choice_type_selector",
                            "label": "Link to",
                            "required": False,
                        },
                    ),
                    2: ("wagtail.blocks.PageChooserBlock", (), {"form_classname": "page_link", "label": "Page", "required": False}),
                    3: ("wagtail.documents.blocks.DocumentChooserBlock", (), {"form_classname": "file_link", "label": "File", "required": False}),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "form_classname": "custom_url_link url_field",
                            "label": "Custom URL",
                            "max_length": 300,
                            "required": False,
                            "validators": [wagtail.admin.forms.choosers.URLOrAbsolutePathValidator()],
                        },
                    ),
                    5: ("wagtail.blocks.CharBlock", (), {"form_classname": "anchor_link", "label": "#", "max_length": 300, "required": False}),
                    6: ("wagtail.blocks.EmailBlock", (), {"required": False}),
                    7: ("wagtail.blocks.CharBlock", (), {"form_classname": "phone_link", "label": "Phone", "max_length": 30, "required": False}),
                    8: ("wagtail.blocks.BooleanBlock", (), {"form_classname": "new_window_toggle", "label": "Open in new window", "required": False}),
                    9: (
                        "wagtail.blocks.StructBlock",
                        [[("link_to", 1), ("page", 2), ("file", 3), ("custom_url", 4), ("anchor", 5), ("email", 6), ("phone", 7), ("new_window", 8)]],
                        {},
                    ),
                    10: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"default": False, "help_text": "This link should look like a button", "required": False},
                    ),
                    11: ("wagtail.blocks.StructBlock", [[("link_text", 0), ("link", 9), ("has_button_appearance", 10)]], {}),
                },
                help_text="Configure the sub-navigation menu items. Leave empty to use the default navigation.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="advertisingindexpage",
            name="content",
            field=wagtail.fields.StreamField(
                [("advertising_hero_block", 13), ("section_header_block", 18), ("figure_with_statistic_block", 23), ("feature_list_block", 26)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional: Add an ID to make this section linkable from navigation (e.g., 'hero', 'overview')",
                            "max_length": 100,
                            "required": False,
                        },
                    ),
                    1: ("wagtail.blocks.CharBlock", (), {"char_max_length": 255}),
                    2: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("page", "Page"),
                                ("file", "File"),
                                ("custom_url", "Custom URL"),
                                ("email", "Email"),
                                ("anchor", "Anchor"),
                                ("phone", "Phone"),
                            ],
                            "classname": "link_choice_type_selector",
                            "label": "Link to",
                            "required": False,
                        },
                    ),
                    3: ("wagtail.blocks.PageChooserBlock", (), {"form_classname": "page_link", "label": "Page", "required": False}),
                    4: ("wagtail.documents.blocks.DocumentChooserBlock", (), {"form_classname": "file_link", "label": "File", "required": False}),
                    5: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "form_classname": "custom_url_link url_field",
                            "label": "Custom URL",
                            "max_length": 300,
                            "required": False,
                            "validators": [wagtail.admin.forms.choosers.URLOrAbsolutePathValidator()],
                        },
                    ),
                    6: ("wagtail.blocks.CharBlock", (), {"form_classname": "anchor_link", "label": "#", "max_length": 300, "required": False}),
                    7: ("wagtail.blocks.EmailBlock", (), {"required": False}),
                    8: ("wagtail.blocks.CharBlock", (), {"form_classname": "phone_link", "label": "Phone", "max_length": 30, "required": False}),
                    9: ("wagtail.blocks.BooleanBlock", (), {"form_classname": "new_window_toggle", "label": "Open in new window", "required": False}),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [[("link_to", 2), ("page", 3), ("file", 4), ("custom_url", 5), ("anchor", 6), ("email", 7), ("phone", 8), ("new_window", 9)]],
                        {"label": "Primary CTA Link"},
                    ),
                    11: ("wagtail.blocks.TextBlock", (), {}),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [[("link_to", 2), ("page", 3), ("file", 4), ("custom_url", 5), ("anchor", 6), ("email", 7), ("phone", 8), ("new_window", 9)]],
                        {"label": "Secondary CTA Link"},
                    ),
                    13: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("anchor_id", 0),
                                ("heading_text", 1),
                                ("primary_cta_text", 1),
                                ("primary_cta_link", 10),
                                ("supporting_text", 11),
                                ("secondary_cta_text", 1),
                                ("secondary_cta_link", 12),
                            ]
                        ],
                        {},
                    ),
                    14: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional: Add an ID to make this section linkable from navigation (e.g., 'solutions', 'why-mozilla')",
                            "max_length": 100,
                            "required": False,
                        },
                    ),
                    15: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"default": False, "inline_form": True, "label": "Should the section have a divider line on top?", "required": False},
                    ),
                    16: ("wagtail.blocks.CharBlock", (), {"char_max_length": 255, "required": False}),
                    17: ("wagtail.images.blocks.ImageChooserBlock", (), {"required": False}),
                    18: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("anchor_id", 14),
                                ("has_top_divider", 15),
                                ("superheading_text", 16),
                                ("heading_text", 1),
                                ("subheading_text", 16),
                                ("image", 17),
                            ]
                        ],
                        {},
                    ),
                    19: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Optional: Add an ID to make this section linkable from navigation", "max_length": 100, "required": False},
                    ),
                    20: ("wagtail.blocks.RichTextBlock", (), {"char_max_length": 255}),
                    21: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"default": False, "inline_form": True, "label": "Should the image be to the right of the statistic?", "required": False},
                    ),
                    22: (
                        "wagtail.blocks.StructBlock",
                        [[("link_to", 2), ("page", 3), ("file", 4), ("custom_url", 5), ("anchor", 6), ("email", 7), ("phone", 8), ("new_window", 9)]],
                        {"label": "Link", "required": False},
                    ),
                    23: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("anchor_id", 19),
                                ("image", 17),
                                ("image_caption", 20),
                                ("statistic_value", 1),
                                ("statistic_label", 1),
                                ("align_image_on_right", 21),
                                ("cta_text", 16),
                                ("cta_link", 22),
                            ]
                        ],
                        {},
                    ),
                    24: ("wagtail.blocks.StructBlock", [[("heading_text", 1), ("supporting_text", 11)]], {}),
                    25: ("wagtail.blocks.ListBlock", (24,), {"min_num": 1}),
                    26: ("wagtail.blocks.StructBlock", [[("anchor_id", 19), ("feature_list_items", 25)]], {}),
                },
                null=True,
            ),
        ),
    ]
