# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.7 on 2025-10-31 18:42

import django.db.models.deletion
from django.db import migrations, models

import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("mozorg", "0013_advertisingindexpage_sub_navigation_and_more"),
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentSubpage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "content",
                    wagtail.fields.StreamField(
                        [("section_header_block", 5)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": (
                                        "Optional: Add an ID to make this section linkable from navigation (e.g., 'solutions', 'why-mozilla')"
                                    ),
                                    "max_length": 100,
                                    "required": False,
                                },
                            ),
                            1: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {"default": False, "inline_form": True, "label": "Should the section have a divider line on top?", "required": False},
                            ),
                            2: ("wagtail.blocks.CharBlock", (), {"char_max_length": 255, "required": False}),
                            3: ("wagtail.blocks.CharBlock", (), {"char_max_length": 255}),
                            4: ("wagtail.images.blocks.ImageChooserBlock", (), {"required": False}),
                            5: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("anchor_id", 0),
                                        ("has_top_divider", 1),
                                        ("superheading_text", 2),
                                        ("heading_text", 3),
                                        ("subheading_text", 2),
                                        ("image", 4),
                                    ]
                                ],
                                {},
                            ),
                        },
                        null=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
