# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.7 on 2025-10-31 19:08

import django.db.models.deletion
from django.db import migrations, models

import wagtail.admin.forms.choosers
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("mozorg", "0014_contentsubpage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advertisingindexpage",
            name="content",
            field=wagtail.fields.StreamField(
                [("advertising_hero_block", 13), ("section_header_block", 19), ("figure_with_statistic_block", 24), ("feature_list_block", 28)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional: Add an ID to make this section linkable from navigation (e.g., 'hero', 'overview')",
                            "max_length": 100,
                            "required": False,
                        },
                    ),
                    1: ("wagtail.blocks.CharBlock", (), {"char_max_length": 255}),
                    2: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("page", "Page"),
                                ("file", "File"),
                                ("custom_url", "Custom URL"),
                                ("email", "Email"),
                                ("anchor", "Anchor"),
                                ("phone", "Phone"),
                            ],
                            "classname": "link_choice_type_selector",
                            "label": "Link to",
                            "required": False,
                        },
                    ),
                    3: ("wagtail.blocks.PageChooserBlock", (), {"form_classname": "page_link", "label": "Page", "required": False}),
                    4: ("wagtail.documents.blocks.DocumentChooserBlock", (), {"form_classname": "file_link", "label": "File", "required": False}),
                    5: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "form_classname": "custom_url_link url_field",
                            "label": "Custom URL",
                            "max_length": 300,
                            "required": False,
                            "validators": [wagtail.admin.forms.choosers.URLOrAbsolutePathValidator()],
                        },
                    ),
                    6: ("wagtail.blocks.CharBlock", (), {"form_classname": "anchor_link", "label": "#", "max_length": 300, "required": False}),
                    7: ("wagtail.blocks.EmailBlock", (), {"required": False}),
                    8: ("wagtail.blocks.CharBlock", (), {"form_classname": "phone_link", "label": "Phone", "max_length": 30, "required": False}),
                    9: ("wagtail.blocks.BooleanBlock", (), {"form_classname": "new_window_toggle", "label": "Open in new window", "required": False}),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [[("link_to", 2), ("page", 3), ("file", 4), ("custom_url", 5), ("anchor", 6), ("email", 7), ("phone", 8), ("new_window", 9)]],
                        {"label": "Primary CTA Link"},
                    ),
                    11: ("wagtail.blocks.TextBlock", (), {}),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [[("link_to", 2), ("page", 3), ("file", 4), ("custom_url", 5), ("anchor", 6), ("email", 7), ("phone", 8), ("new_window", 9)]],
                        {"label": "Secondary CTA Link"},
                    ),
                    13: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("anchor_id", 0),
                                ("heading_text", 1),
                                ("primary_cta_text", 1),
                                ("primary_cta_link", 10),
                                ("supporting_text", 11),
                                ("secondary_cta_text", 1),
                                ("secondary_cta_link", 12),
                            ]
                        ],
                        {},
                    ),
                    14: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional: Add an ID to make this section linkable from navigation (e.g., 'solutions', 'why-mozilla')",
                            "max_length": 100,
                            "required": False,
                        },
                    ),
                    15: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"default": False, "inline_form": True, "label": "Should the section have a divider line on top?", "required": False},
                    ),
                    16: ("wagtail.blocks.CharBlock", (), {"char_max_length": 255, "required": False}),
                    17: ("wagtail.images.blocks.ImageChooserBlock", (), {"required": False}),
                    18: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"default": False, "inline_form": True, "label": "Should the section have a dark background?", "required": False},
                    ),
                    19: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("anchor_id", 14),
                                ("has_top_divider", 15),
                                ("superheading_text", 16),
                                ("heading_text", 16),
                                ("subheading_text", 16),
                                ("image", 17),
                                ("display_on_dark_background", 18),
                            ]
                        ],
                        {},
                    ),
                    20: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Optional: Add an ID to make this section linkable from navigation", "max_length": 100, "required": False},
                    ),
                    21: ("wagtail.blocks.RichTextBlock", (), {"char_max_length": 255, "required": False}),
                    22: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"default": False, "inline_form": True, "label": "Should the image be to the right of the statistic?", "required": False},
                    ),
                    23: (
                        "wagtail.blocks.StructBlock",
                        [[("link_to", 2), ("page", 3), ("file", 4), ("custom_url", 5), ("anchor", 6), ("email", 7), ("phone", 8), ("new_window", 9)]],
                        {"label": "Link", "required": False},
                    ),
                    24: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("anchor_id", 20),
                                ("image", 17),
                                ("image_caption", 21),
                                ("statistic_value", 1),
                                ("statistic_label", 1),
                                ("align_image_on_right", 22),
                                ("cta_text", 16),
                                ("cta_link", 23),
                                ("display_on_dark_background", 18),
                            ]
                        ],
                        {},
                    ),
                    25: ("wagtail.blocks.RichTextBlock", (), {"features": ["bold", "italic", "link"]}),
                    26: ("wagtail.blocks.StructBlock", [[("heading_text", 11), ("supporting_text", 25)]], {}),
                    27: ("wagtail.blocks.ListBlock", (26,), {"min_num": 1}),
                    28: ("wagtail.blocks.StructBlock", [[("anchor_id", 20), ("feature_list_items", 27)]], {}),
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="contentsubpage",
            name="content",
            field=wagtail.fields.StreamField(
                [
                    ("section_header_block", 5),
                    ("figure_with_statistic_block", 19),
                    ("statistic_callout_block", 22),
                    ("features_with_modals", 30),
                    ("feature_list_block", 34),
                    ("text_and_link", 36),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional: Add an ID to make this section linkable from navigation (e.g., 'solutions', 'why-mozilla')",
                            "max_length": 100,
                            "required": False,
                        },
                    ),
                    1: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"default": False, "inline_form": True, "label": "Should the section have a divider line on top?", "required": False},
                    ),
                    2: ("wagtail.blocks.CharBlock", (), {"char_max_length": 255, "required": False}),
                    3: ("wagtail.images.blocks.ImageChooserBlock", (), {"required": False}),
                    4: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"default": False, "inline_form": True, "label": "Should the section have a dark background?", "required": False},
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("anchor_id", 0),
                                ("has_top_divider", 1),
                                ("superheading_text", 2),
                                ("heading_text", 2),
                                ("subheading_text", 2),
                                ("image", 3),
                                ("display_on_dark_background", 4),
                            ]
                        ],
                        {},
                    ),
                    6: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Optional: Add an ID to make this section linkable from navigation", "max_length": 100, "required": False},
                    ),
                    7: ("wagtail.blocks.RichTextBlock", (), {"char_max_length": 255, "required": False}),
                    8: ("wagtail.blocks.CharBlock", (), {"char_max_length": 255}),
                    9: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"default": False, "inline_form": True, "label": "Should the image be to the right of the statistic?", "required": False},
                    ),
                    10: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("page", "Page"),
                                ("file", "File"),
                                ("custom_url", "Custom URL"),
                                ("email", "Email"),
                                ("anchor", "Anchor"),
                                ("phone", "Phone"),
                            ],
                            "classname": "link_choice_type_selector",
                            "label": "Link to",
                            "required": False,
                        },
                    ),
                    11: ("wagtail.blocks.PageChooserBlock", (), {"form_classname": "page_link", "label": "Page", "required": False}),
                    12: ("wagtail.documents.blocks.DocumentChooserBlock", (), {"form_classname": "file_link", "label": "File", "required": False}),
                    13: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "form_classname": "custom_url_link url_field",
                            "label": "Custom URL",
                            "max_length": 300,
                            "required": False,
                            "validators": [wagtail.admin.forms.choosers.URLOrAbsolutePathValidator()],
                        },
                    ),
                    14: ("wagtail.blocks.CharBlock", (), {"form_classname": "anchor_link", "label": "#", "max_length": 300, "required": False}),
                    15: ("wagtail.blocks.EmailBlock", (), {"required": False}),
                    16: ("wagtail.blocks.CharBlock", (), {"form_classname": "phone_link", "label": "Phone", "max_length": 30, "required": False}),
                    17: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"form_classname": "new_window_toggle", "label": "Open in new window", "required": False},
                    ),
                    18: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("link_to", 10),
                                ("page", 11),
                                ("file", 12),
                                ("custom_url", 13),
                                ("anchor", 14),
                                ("email", 15),
                                ("phone", 16),
                                ("new_window", 17),
                            ]
                        ],
                        {"label": "Link", "required": False},
                    ),
                    19: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("anchor_id", 6),
                                ("image", 3),
                                ("image_caption", 7),
                                ("statistic_value", 8),
                                ("statistic_label", 8),
                                ("align_image_on_right", 9),
                                ("cta_text", 2),
                                ("cta_link", 18),
                                ("display_on_dark_background", 4),
                            ]
                        ],
                        {},
                    ),
                    20: ("wagtail.blocks.StructBlock", [[("statistic_superlabel", 2), ("statistic_value", 8), ("statistic_label", 8)]], {}),
                    21: ("wagtail.blocks.ListBlock", (20,), {"min_num": 1}),
                    22: (
                        "wagtail.blocks.StructBlock",
                        [[("anchor_id", 6), ("heading_text", 8), ("statistics", 21), ("display_on_dark_background", 4)]],
                        {},
                    ),
                    23: ("wagtail.blocks.TextBlock", (), {}),
                    24: ("wagtail.blocks.TextBlock", (), {"char_max_length": 255, "required": False}),
                    25: ("wagtail.blocks.StructBlock", [[("image", 3), ("image_caption_heading", 24), ("image_caption_text", 24)]], {}),
                    26: ("wagtail.blocks.ListBlock", (25,), {"min_num": 1}),
                    27: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("link_to", 10),
                                ("page", 11),
                                ("file", 12),
                                ("custom_url", 13),
                                ("anchor", 14),
                                ("email", 15),
                                ("phone", 16),
                                ("new_window", 17),
                            ]
                        ],
                        {"label": "CTA Link", "required": False},
                    ),
                    28: ("wagtail.blocks.StructBlock", [[("heading_text", 8), ("figures", 26), ("cta_text", 2), ("cta_link", 27)]], {}),
                    29: ("wagtail.blocks.ListBlock", (28,), {"min_num": 1}),
                    30: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("anchor_id", 6),
                                ("heading_text", 8),
                                ("supporting_text", 23),
                                ("feature_list_items", 29),
                                ("display_on_dark_background", 4),
                            ]
                        ],
                        {},
                    ),
                    31: ("wagtail.blocks.RichTextBlock", (), {"features": ["bold", "italic", "link"]}),
                    32: ("wagtail.blocks.StructBlock", [[("heading_text", 23), ("supporting_text", 31)]], {}),
                    33: ("wagtail.blocks.ListBlock", (32,), {"min_num": 1}),
                    34: ("wagtail.blocks.StructBlock", [[("anchor_id", 6), ("feature_list_items", 33)]], {}),
                    35: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("link_to", 10),
                                ("page", 11),
                                ("file", 12),
                                ("custom_url", 13),
                                ("anchor", 14),
                                ("email", 15),
                                ("phone", 16),
                                ("new_window", 17),
                            ]
                        ],
                        {"label": "Link"},
                    ),
                    36: ("wagtail.blocks.StructBlock", [[("text", 8), ("link_text", 8), ("link", 35), ("display_on_dark_background", 4)]], {}),
                },
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="contentsubpage",
            name="contact_banner",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="mozorg.contactbannersnippet"
            ),
        ),
        migrations.AddField(
            model_name="contentsubpage",
            name="notifications",
            field=wagtail.fields.StreamField(
                [("notification_block", 13)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"char_max_length": 255, "features": ["bold", "italic", "superscript", "subscript", "strikethrough", "code", "link"]},
                    ),
                    1: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("linkedin", "LinkedIn"),
                                ("tiktok", "TikTok"),
                                ("spotify", "Spotify"),
                                ("twitter", "Twitter"),
                                ("bluesky", "BlueSky"),
                                ("instagram", "Instagram"),
                                ("youtube", "YouTube"),
                            ],
                            "inline_form": True,
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("page", "Page"),
                                ("file", "File"),
                                ("custom_url", "Custom URL"),
                                ("email", "Email"),
                                ("anchor", "Anchor"),
                                ("phone", "Phone"),
                            ],
                            "classname": "link_choice_type_selector",
                            "label": "Link to",
                            "required": False,
                        },
                    ),
                    3: ("wagtail.blocks.PageChooserBlock", (), {"form_classname": "page_link", "label": "Page", "required": False}),
                    4: ("wagtail.documents.blocks.DocumentChooserBlock", (), {"form_classname": "file_link", "label": "File", "required": False}),
                    5: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "form_classname": "custom_url_link url_field",
                            "label": "Custom URL",
                            "max_length": 300,
                            "required": False,
                            "validators": [wagtail.admin.forms.choosers.URLOrAbsolutePathValidator()],
                        },
                    ),
                    6: ("wagtail.blocks.CharBlock", (), {"form_classname": "anchor_link", "label": "#", "max_length": 300, "required": False}),
                    7: ("wagtail.blocks.EmailBlock", (), {"required": False}),
                    8: ("wagtail.blocks.CharBlock", (), {"form_classname": "phone_link", "label": "Phone", "max_length": 30, "required": False}),
                    9: ("wagtail.blocks.BooleanBlock", (), {"form_classname": "new_window_toggle", "label": "Open in new window", "required": False}),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [[("link_to", 2), ("page", 3), ("file", 4), ("custom_url", 5), ("anchor", 6), ("email", 7), ("phone", 8), ("new_window", 9)]],
                        {},
                    ),
                    11: ("wagtail.blocks.StructBlock", [[("icon", 1), ("link", 10)]], {}),
                    12: ("wagtail.blocks.StreamBlock", [[("link_with_icon", 11)]], {"required": False}),
                    13: ("wagtail.blocks.StructBlock", [[("notification_text", 0), ("links", 12)]], {}),
                },
                null=True,
            ),
        ),
    ]
