# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.7 on 2025-11-12 19:29

from django.db import migrations

import wagtail.admin.forms.choosers
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("mozorg", "0015_alter_advertisingindexpage_content_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="advertisingindexpage",
            name="content",
        ),
        migrations.RemoveField(
            model_name="contentsubpage",
            name="content",
        ),
        migrations.AddField(
            model_name="advertisingindexpage",
            name="hero",
            field=wagtail.fields.StreamField(
                [("advertising_hero_block", 13)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional: Add an ID to make this section linkable from navigation (e.g., 'hero', 'overview')",
                            "max_length": 100,
                            "required": False,
                        },
                    ),
                    1: ("wagtail.blocks.CharBlock", (), {"char_max_length": 255}),
                    2: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("page", "Page"),
                                ("file", "File"),
                                ("custom_url", "Custom URL"),
                                ("email", "Email"),
                                ("anchor", "Anchor"),
                                ("phone", "Phone"),
                            ],
                            "classname": "link_choice_type_selector",
                            "label": "Link to",
                            "required": False,
                        },
                    ),
                    3: ("wagtail.blocks.PageChooserBlock", (), {"form_classname": "page_link", "label": "Page", "required": False}),
                    4: ("wagtail.documents.blocks.DocumentChooserBlock", (), {"form_classname": "file_link", "label": "File", "required": False}),
                    5: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "form_classname": "custom_url_link url_field",
                            "label": "Custom URL",
                            "max_length": 300,
                            "required": False,
                            "validators": [wagtail.admin.forms.choosers.URLOrAbsolutePathValidator()],
                        },
                    ),
                    6: ("wagtail.blocks.CharBlock", (), {"form_classname": "anchor_link", "label": "#", "max_length": 300, "required": False}),
                    7: ("wagtail.blocks.EmailBlock", (), {"required": False}),
                    8: ("wagtail.blocks.CharBlock", (), {"form_classname": "phone_link", "label": "Phone", "max_length": 30, "required": False}),
                    9: ("wagtail.blocks.BooleanBlock", (), {"form_classname": "new_window_toggle", "label": "Open in new window", "required": False}),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [[("link_to", 2), ("page", 3), ("file", 4), ("custom_url", 5), ("anchor", 6), ("email", 7), ("phone", 8), ("new_window", 9)]],
                        {"label": "Primary CTA Link"},
                    ),
                    11: ("wagtail.blocks.TextBlock", (), {}),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [[("link_to", 2), ("page", 3), ("file", 4), ("custom_url", 5), ("anchor", 6), ("email", 7), ("phone", 8), ("new_window", 9)]],
                        {"label": "Secondary CTA Link"},
                    ),
                    13: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("anchor_id", 0),
                                ("heading_text", 1),
                                ("primary_cta_text", 1),
                                ("primary_cta_link", 10),
                                ("supporting_text", 11),
                                ("secondary_cta_text", 1),
                                ("secondary_cta_link", 12),
                            ]
                        ],
                        {},
                    ),
                },
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="advertisingindexpage",
            name="sections",
            field=wagtail.fields.StreamField(
                [("section", 38)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional: Add an ID to make this section linkable from navigation (e.g., 'solutions', 'why-mozilla')",
                            "max_length": 100,
                            "required": False,
                        },
                    ),
                    1: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"default": False, "inline_form": True, "label": "Should the section have a divider line on top?", "required": False},
                    ),
                    2: ("wagtail.blocks.CharBlock", (), {"char_max_length": 255, "required": False}),
                    3: ("wagtail.images.blocks.ImageChooserBlock", (), {"required": False}),
                    4: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"default": False, "inline_form": True, "label": "Should the section have a dark background?", "required": False},
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("anchor_id", 0),
                                ("has_top_divider", 1),
                                ("superheading_text", 2),
                                ("heading_text", 2),
                                ("subheading_text", 2),
                                ("image", 3),
                                ("display_on_dark_background", 4),
                            ]
                        ],
                        {},
                    ),
                    6: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Optional: Add an ID to make this section linkable from navigation", "max_length": 100, "required": False},
                    ),
                    7: ("wagtail.blocks.RichTextBlock", (), {"char_max_length": 255, "required": False}),
                    8: ("wagtail.blocks.CharBlock", (), {"char_max_length": 255}),
                    9: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"default": False, "inline_form": True, "label": "Should the image be to the right of the statistic?", "required": False},
                    ),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("anchor_id", 6),
                                ("image", 3),
                                ("image_caption", 7),
                                ("statistic_value", 8),
                                ("statistic_label", 8),
                                ("align_image_on_right", 9),
                                ("display_on_dark_background", 4),
                            ]
                        ],
                        {},
                    ),
                    11: ("wagtail.blocks.StructBlock", [[("statistic_superlabel", 2), ("statistic_value", 8), ("statistic_label", 8)]], {}),
                    12: ("wagtail.blocks.ListBlock", (11,), {"min_num": 1}),
                    13: (
                        "wagtail.blocks.StructBlock",
                        [[("anchor_id", 6), ("heading_text", 8), ("statistics", 12), ("display_on_dark_background", 4)]],
                        {},
                    ),
                    14: ("wagtail.blocks.TextBlock", (), {}),
                    15: ("wagtail.blocks.TextBlock", (), {"char_max_length": 255, "required": False}),
                    16: ("wagtail.blocks.StructBlock", [[("image", 3), ("image_caption_heading", 15), ("image_caption_text", 15)]], {}),
                    17: ("wagtail.blocks.ListBlock", (16,), {"min_num": 1}),
                    18: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("page", "Page"),
                                ("file", "File"),
                                ("custom_url", "Custom URL"),
                                ("email", "Email"),
                                ("anchor", "Anchor"),
                                ("phone", "Phone"),
                            ],
                            "classname": "link_choice_type_selector",
                            "label": "Link to",
                            "required": False,
                        },
                    ),
                    19: ("wagtail.blocks.PageChooserBlock", (), {"form_classname": "page_link", "label": "Page", "required": False}),
                    20: ("wagtail.documents.blocks.DocumentChooserBlock", (), {"form_classname": "file_link", "label": "File", "required": False}),
                    21: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "form_classname": "custom_url_link url_field",
                            "label": "Custom URL",
                            "max_length": 300,
                            "required": False,
                            "validators": [wagtail.admin.forms.choosers.URLOrAbsolutePathValidator()],
                        },
                    ),
                    22: ("wagtail.blocks.CharBlock", (), {"form_classname": "anchor_link", "label": "#", "max_length": 300, "required": False}),
                    23: ("wagtail.blocks.EmailBlock", (), {"required": False}),
                    24: ("wagtail.blocks.CharBlock", (), {"form_classname": "phone_link", "label": "Phone", "max_length": 30, "required": False}),
                    25: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"form_classname": "new_window_toggle", "label": "Open in new window", "required": False},
                    ),
                    26: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("link_to", 18),
                                ("page", 19),
                                ("file", 20),
                                ("custom_url", 21),
                                ("anchor", 22),
                                ("email", 23),
                                ("phone", 24),
                                ("new_window", 25),
                            ]
                        ],
                        {"label": "CTA Link", "required": False},
                    ),
                    27: ("wagtail.blocks.StructBlock", [[("heading_text", 8), ("figures", 17), ("cta_text", 2), ("cta_link", 26)]], {}),
                    28: ("wagtail.blocks.ListBlock", (27,), {"min_num": 1}),
                    29: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("anchor_id", 6),
                                ("heading_text", 8),
                                ("supporting_text", 14),
                                ("feature_list_items", 28),
                                ("display_on_dark_background", 4),
                            ]
                        ],
                        {},
                    ),
                    30: ("wagtail.blocks.RichTextBlock", (), {"features": ["bold", "italic", "link"]}),
                    31: ("wagtail.blocks.StructBlock", [[("heading_text", 14), ("supporting_text", 30)]], {}),
                    32: ("wagtail.blocks.ListBlock", (31,), {"min_num": 1}),
                    33: ("wagtail.blocks.StructBlock", [[("anchor_id", 6), ("feature_list_items", 32)]], {}),
                    34: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("section_header_block", 5),
                                ("figure_with_statistic_block", 10),
                                ("statistic_callout_block", 13),
                                ("features_with_modals", 29),
                                ("feature_list_block", 33),
                            ]
                        ],
                        {},
                    ),
                    35: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("link_to", 18),
                                ("page", 19),
                                ("file", 20),
                                ("custom_url", 21),
                                ("anchor", 22),
                                ("email", 23),
                                ("phone", 24),
                                ("new_window", 25),
                            ]
                        ],
                        {"label": "Link"},
                    ),
                    36: ("wagtail.blocks.StructBlock", [[("text", 2), ("link_text", 8), ("link", 35), ("display_on_dark_background", 4)]], {}),
                    37: ("wagtail.blocks.ListBlock", (36,), {"default": [], "label": "Call to Action", "max_num": 1, "min_num": 0}),
                    38: ("wagtail.blocks.StructBlock", [[("header", 5), ("content", 34), ("call_to_action", 37)]], {}),
                },
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="contentsubpage",
            name="sections",
            field=wagtail.fields.StreamField(
                [("section", 38)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional: Add an ID to make this section linkable from navigation (e.g., 'solutions', 'why-mozilla')",
                            "max_length": 100,
                            "required": False,
                        },
                    ),
                    1: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"default": False, "inline_form": True, "label": "Should the section have a divider line on top?", "required": False},
                    ),
                    2: ("wagtail.blocks.CharBlock", (), {"char_max_length": 255, "required": False}),
                    3: ("wagtail.images.blocks.ImageChooserBlock", (), {"required": False}),
                    4: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"default": False, "inline_form": True, "label": "Should the section have a dark background?", "required": False},
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("anchor_id", 0),
                                ("has_top_divider", 1),
                                ("superheading_text", 2),
                                ("heading_text", 2),
                                ("subheading_text", 2),
                                ("image", 3),
                                ("display_on_dark_background", 4),
                            ]
                        ],
                        {},
                    ),
                    6: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Optional: Add an ID to make this section linkable from navigation", "max_length": 100, "required": False},
                    ),
                    7: ("wagtail.blocks.RichTextBlock", (), {"char_max_length": 255, "required": False}),
                    8: ("wagtail.blocks.CharBlock", (), {"char_max_length": 255}),
                    9: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"default": False, "inline_form": True, "label": "Should the image be to the right of the statistic?", "required": False},
                    ),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("anchor_id", 6),
                                ("image", 3),
                                ("image_caption", 7),
                                ("statistic_value", 8),
                                ("statistic_label", 8),
                                ("align_image_on_right", 9),
                                ("display_on_dark_background", 4),
                            ]
                        ],
                        {},
                    ),
                    11: ("wagtail.blocks.StructBlock", [[("statistic_superlabel", 2), ("statistic_value", 8), ("statistic_label", 8)]], {}),
                    12: ("wagtail.blocks.ListBlock", (11,), {"min_num": 1}),
                    13: (
                        "wagtail.blocks.StructBlock",
                        [[("anchor_id", 6), ("heading_text", 8), ("statistics", 12), ("display_on_dark_background", 4)]],
                        {},
                    ),
                    14: ("wagtail.blocks.TextBlock", (), {}),
                    15: ("wagtail.blocks.TextBlock", (), {"char_max_length": 255, "required": False}),
                    16: ("wagtail.blocks.StructBlock", [[("image", 3), ("image_caption_heading", 15), ("image_caption_text", 15)]], {}),
                    17: ("wagtail.blocks.ListBlock", (16,), {"min_num": 1}),
                    18: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("page", "Page"),
                                ("file", "File"),
                                ("custom_url", "Custom URL"),
                                ("email", "Email"),
                                ("anchor", "Anchor"),
                                ("phone", "Phone"),
                            ],
                            "classname": "link_choice_type_selector",
                            "label": "Link to",
                            "required": False,
                        },
                    ),
                    19: ("wagtail.blocks.PageChooserBlock", (), {"form_classname": "page_link", "label": "Page", "required": False}),
                    20: ("wagtail.documents.blocks.DocumentChooserBlock", (), {"form_classname": "file_link", "label": "File", "required": False}),
                    21: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "form_classname": "custom_url_link url_field",
                            "label": "Custom URL",
                            "max_length": 300,
                            "required": False,
                            "validators": [wagtail.admin.forms.choosers.URLOrAbsolutePathValidator()],
                        },
                    ),
                    22: ("wagtail.blocks.CharBlock", (), {"form_classname": "anchor_link", "label": "#", "max_length": 300, "required": False}),
                    23: ("wagtail.blocks.EmailBlock", (), {"required": False}),
                    24: ("wagtail.blocks.CharBlock", (), {"form_classname": "phone_link", "label": "Phone", "max_length": 30, "required": False}),
                    25: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"form_classname": "new_window_toggle", "label": "Open in new window", "required": False},
                    ),
                    26: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("link_to", 18),
                                ("page", 19),
                                ("file", 20),
                                ("custom_url", 21),
                                ("anchor", 22),
                                ("email", 23),
                                ("phone", 24),
                                ("new_window", 25),
                            ]
                        ],
                        {"label": "CTA Link", "required": False},
                    ),
                    27: ("wagtail.blocks.StructBlock", [[("heading_text", 8), ("figures", 17), ("cta_text", 2), ("cta_link", 26)]], {}),
                    28: ("wagtail.blocks.ListBlock", (27,), {"min_num": 1}),
                    29: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("anchor_id", 6),
                                ("heading_text", 8),
                                ("supporting_text", 14),
                                ("feature_list_items", 28),
                                ("display_on_dark_background", 4),
                            ]
                        ],
                        {},
                    ),
                    30: ("wagtail.blocks.RichTextBlock", (), {"features": ["bold", "italic", "link"]}),
                    31: ("wagtail.blocks.StructBlock", [[("heading_text", 14), ("supporting_text", 30)]], {}),
                    32: ("wagtail.blocks.ListBlock", (31,), {"min_num": 1}),
                    33: ("wagtail.blocks.StructBlock", [[("anchor_id", 6), ("feature_list_items", 32)]], {}),
                    34: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("section_header_block", 5),
                                ("figure_with_statistic_block", 10),
                                ("statistic_callout_block", 13),
                                ("features_with_modals", 29),
                                ("feature_list_block", 33),
                            ]
                        ],
                        {},
                    ),
                    35: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("link_to", 18),
                                ("page", 19),
                                ("file", 20),
                                ("custom_url", 21),
                                ("anchor", 22),
                                ("email", 23),
                                ("phone", 24),
                                ("new_window", 25),
                            ]
                        ],
                        {"label": "Link"},
                    ),
                    36: ("wagtail.blocks.StructBlock", [[("text", 2), ("link_text", 8), ("link", 35), ("display_on_dark_background", 4)]], {}),
                    37: ("wagtail.blocks.ListBlock", (36,), {"default": [], "label": "Call to Action", "max_num": 1, "min_num": 0}),
                    38: ("wagtail.blocks.StructBlock", [[("header", 5), ("content", 34), ("call_to_action", 37)]], {}),
                },
                null=True,
            ),
        ),
    ]
