# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.8 on 2025-11-21 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mozorg", "0017_alter_advertisingindexpage_sections_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationSnippet",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("notification_text", models.CharField(max_length=255)),
                ("linkedin_link", models.URLField(blank=True, max_length=255)),
                ("tiktok_link", models.URLField(blank=True, max_length=255)),
                ("spotify_link", models.URLField(blank=True, max_length=255)),
                ("twitter_link", models.URLField(blank=True, max_length=255)),
                ("bluesky_link", models.URLField(blank=True, max_length=255)),
                ("instagram_link", models.URLField(blank=True, max_length=255)),
                ("youtube_link", models.URLField(blank=True, max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name="advertisingindexpage",
            name="notifications",
        ),
        migrations.RemoveField(
            model_name="contentsubpage",
            name="notifications",
        ),
        migrations.AddField(
            model_name="advertisingindexpage",
            name="notification",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="mozorg.notificationsnippet"
            ),
        ),
        migrations.AddField(
            model_name="contentsubpage",
            name="notification",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="mozorg.notificationsnippet"
            ),
        ),
    ]
