# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.8 on 2025-11-24 18:10

from django.db import migrations

import wagtail.admin.forms.choosers
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("mozorg", "0018_notificationsnippet_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notificationsnippet",
            name="twitter_link",
        ),
        migrations.AlterField(
            model_name="advertisingindexpage",
            name="sections",
            field=wagtail.fields.StreamField(
                [("section", 39)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional: Add an ID to make this section linkable from navigation (e.g., 'solutions', 'why-mozilla')",
                            "max_length": 100,
                            "required": False,
                        },
                    ),
                    1: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"default": False, "inline_form": True, "label": "Should the section have a divider line on top?", "required": False},
                    ),
                    2: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"default": False, "inline_form": True, "label": "Should the section have a dark background?", "required": False},
                    ),
                    3: ("wagtail.blocks.StructBlock", [[("anchor_id", 0), ("has_top_divider", 1), ("display_on_dark_background", 2)]], {}),
                    4: ("wagtail.blocks.CharBlock", (), {"char_max_length": 255, "required": False}),
                    5: ("wagtail.images.blocks.ImageChooserBlock", (), {"required": False}),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [[("anchor_id", 0), ("superheading_text", 4), ("heading_text", 4), ("subheading_text", 4), ("image", 5)]],
                        {},
                    ),
                    7: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Optional: Add an ID to make this section linkable from navigation", "max_length": 100, "required": False},
                    ),
                    8: ("wagtail.blocks.RichTextBlock", (), {"char_max_length": 255, "required": False}),
                    9: ("wagtail.blocks.CharBlock", (), {"char_max_length": 255}),
                    10: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"default": False, "inline_form": True, "label": "Position the image to the right of the statistic", "required": False},
                    ),
                    11: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("anchor_id", 7),
                                ("image", 5),
                                ("image_caption", 8),
                                ("statistic_value", 9),
                                ("statistic_label", 9),
                                ("align_image_on_right", 10),
                            ]
                        ],
                        {},
                    ),
                    12: ("wagtail.blocks.StructBlock", [[("statistic_superlabel", 4), ("statistic_value", 9), ("statistic_label", 9)]], {}),
                    13: ("wagtail.blocks.ListBlock", (12,), {"min_num": 1}),
                    14: ("wagtail.blocks.StructBlock", [[("anchor_id", 7), ("heading_text", 9), ("statistics", 13)]], {}),
                    15: ("wagtail.blocks.TextBlock", (), {}),
                    16: ("wagtail.blocks.TextBlock", (), {"char_max_length": 255, "required": False}),
                    17: ("wagtail.blocks.StructBlock", [[("image", 5), ("image_caption_heading", 16), ("image_caption_text", 16)]], {}),
                    18: ("wagtail.blocks.ListBlock", (17,), {"min_num": 1}),
                    19: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("page", "Page"),
                                ("file", "File"),
                                ("custom_url", "Custom URL"),
                                ("email", "Email"),
                                ("anchor", "Anchor"),
                                ("phone", "Phone"),
                            ],
                            "classname": "link_choice_type_selector",
                            "label": "Link to",
                            "required": False,
                        },
                    ),
                    20: ("wagtail.blocks.PageChooserBlock", (), {"form_classname": "page_link", "label": "Page", "required": False}),
                    21: ("wagtail.documents.blocks.DocumentChooserBlock", (), {"form_classname": "file_link", "label": "File", "required": False}),
                    22: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "form_classname": "custom_url_link url_field",
                            "label": "Custom URL",
                            "max_length": 300,
                            "required": False,
                            "validators": [wagtail.admin.forms.choosers.URLOrAbsolutePathValidator()],
                        },
                    ),
                    23: ("wagtail.blocks.CharBlock", (), {"form_classname": "anchor_link", "label": "#", "max_length": 300, "required": False}),
                    24: ("wagtail.blocks.EmailBlock", (), {"required": False}),
                    25: ("wagtail.blocks.CharBlock", (), {"form_classname": "phone_link", "label": "Phone", "max_length": 30, "required": False}),
                    26: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"form_classname": "new_window_toggle", "label": "Open in new window", "required": False},
                    ),
                    27: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("link_to", 19),
                                ("page", 20),
                                ("file", 21),
                                ("custom_url", 22),
                                ("anchor", 23),
                                ("email", 24),
                                ("phone", 25),
                                ("new_window", 26),
                            ]
                        ],
                        {"label": "CTA Link", "required": False},
                    ),
                    28: ("wagtail.blocks.StructBlock", [[("heading_text", 9), ("figures", 18), ("cta_text", 4), ("cta_link", 27)]], {}),
                    29: ("wagtail.blocks.ListBlock", (28,), {"min_num": 1}),
                    30: (
                        "wagtail.blocks.StructBlock",
                        [[("anchor_id", 7), ("heading_text", 9), ("supporting_text", 15), ("feature_list_items", 29)]],
                        {},
                    ),
                    31: ("wagtail.blocks.RichTextBlock", (), {"features": ["bold", "italic", "link"]}),
                    32: ("wagtail.blocks.StructBlock", [[("heading_text", 15), ("supporting_text", 31)]], {}),
                    33: ("wagtail.blocks.ListBlock", (32,), {"min_num": 1}),
                    34: ("wagtail.blocks.StructBlock", [[("anchor_id", 7), ("feature_list_items", 33)]], {}),
                    35: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("section_header_block", 6),
                                ("figure_with_statistic_block", 11),
                                ("statistic_callout_block", 14),
                                ("features_with_modals", 30),
                                ("feature_list_block", 34),
                            ]
                        ],
                        {},
                    ),
                    36: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("link_to", 19),
                                ("page", 20),
                                ("file", 21),
                                ("custom_url", 22),
                                ("anchor", 23),
                                ("email", 24),
                                ("phone", 25),
                                ("new_window", 26),
                            ]
                        ],
                        {"label": "Link"},
                    ),
                    37: ("wagtail.blocks.StructBlock", [[("text", 4), ("link_text", 9), ("link", 36)]], {}),
                    38: ("wagtail.blocks.ListBlock", (37,), {"default": [], "label": "Call to Action", "max_num": 1, "min_num": 0}),
                    39: ("wagtail.blocks.StructBlock", [[("settings", 3), ("header", 6), ("content", 35), ("call_to_action", 38)]], {}),
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="contentsubpage",
            name="sections",
            field=wagtail.fields.StreamField(
                [("section", 39)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional: Add an ID to make this section linkable from navigation (e.g., 'solutions', 'why-mozilla')",
                            "max_length": 100,
                            "required": False,
                        },
                    ),
                    1: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"default": False, "inline_form": True, "label": "Should the section have a divider line on top?", "required": False},
                    ),
                    2: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"default": False, "inline_form": True, "label": "Should the section have a dark background?", "required": False},
                    ),
                    3: ("wagtail.blocks.StructBlock", [[("anchor_id", 0), ("has_top_divider", 1), ("display_on_dark_background", 2)]], {}),
                    4: ("wagtail.blocks.CharBlock", (), {"char_max_length": 255, "required": False}),
                    5: ("wagtail.images.blocks.ImageChooserBlock", (), {"required": False}),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [[("anchor_id", 0), ("superheading_text", 4), ("heading_text", 4), ("subheading_text", 4), ("image", 5)]],
                        {},
                    ),
                    7: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Optional: Add an ID to make this section linkable from navigation", "max_length": 100, "required": False},
                    ),
                    8: ("wagtail.blocks.RichTextBlock", (), {"char_max_length": 255, "required": False}),
                    9: ("wagtail.blocks.CharBlock", (), {"char_max_length": 255}),
                    10: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"default": False, "inline_form": True, "label": "Position the image to the right of the statistic", "required": False},
                    ),
                    11: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("anchor_id", 7),
                                ("image", 5),
                                ("image_caption", 8),
                                ("statistic_value", 9),
                                ("statistic_label", 9),
                                ("align_image_on_right", 10),
                            ]
                        ],
                        {},
                    ),
                    12: ("wagtail.blocks.StructBlock", [[("statistic_superlabel", 4), ("statistic_value", 9), ("statistic_label", 9)]], {}),
                    13: ("wagtail.blocks.ListBlock", (12,), {"min_num": 1}),
                    14: ("wagtail.blocks.StructBlock", [[("anchor_id", 7), ("heading_text", 9), ("statistics", 13)]], {}),
                    15: ("wagtail.blocks.TextBlock", (), {}),
                    16: ("wagtail.blocks.TextBlock", (), {"char_max_length": 255, "required": False}),
                    17: ("wagtail.blocks.StructBlock", [[("image", 5), ("image_caption_heading", 16), ("image_caption_text", 16)]], {}),
                    18: ("wagtail.blocks.ListBlock", (17,), {"min_num": 1}),
                    19: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("page", "Page"),
                                ("file", "File"),
                                ("custom_url", "Custom URL"),
                                ("email", "Email"),
                                ("anchor", "Anchor"),
                                ("phone", "Phone"),
                            ],
                            "classname": "link_choice_type_selector",
                            "label": "Link to",
                            "required": False,
                        },
                    ),
                    20: ("wagtail.blocks.PageChooserBlock", (), {"form_classname": "page_link", "label": "Page", "required": False}),
                    21: ("wagtail.documents.blocks.DocumentChooserBlock", (), {"form_classname": "file_link", "label": "File", "required": False}),
                    22: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "form_classname": "custom_url_link url_field",
                            "label": "Custom URL",
                            "max_length": 300,
                            "required": False,
                            "validators": [wagtail.admin.forms.choosers.URLOrAbsolutePathValidator()],
                        },
                    ),
                    23: ("wagtail.blocks.CharBlock", (), {"form_classname": "anchor_link", "label": "#", "max_length": 300, "required": False}),
                    24: ("wagtail.blocks.EmailBlock", (), {"required": False}),
                    25: ("wagtail.blocks.CharBlock", (), {"form_classname": "phone_link", "label": "Phone", "max_length": 30, "required": False}),
                    26: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"form_classname": "new_window_toggle", "label": "Open in new window", "required": False},
                    ),
                    27: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("link_to", 19),
                                ("page", 20),
                                ("file", 21),
                                ("custom_url", 22),
                                ("anchor", 23),
                                ("email", 24),
                                ("phone", 25),
                                ("new_window", 26),
                            ]
                        ],
                        {"label": "CTA Link", "required": False},
                    ),
                    28: ("wagtail.blocks.StructBlock", [[("heading_text", 9), ("figures", 18), ("cta_text", 4), ("cta_link", 27)]], {}),
                    29: ("wagtail.blocks.ListBlock", (28,), {"min_num": 1}),
                    30: (
                        "wagtail.blocks.StructBlock",
                        [[("anchor_id", 7), ("heading_text", 9), ("supporting_text", 15), ("feature_list_items", 29)]],
                        {},
                    ),
                    31: ("wagtail.blocks.RichTextBlock", (), {"features": ["bold", "italic", "link"]}),
                    32: ("wagtail.blocks.StructBlock", [[("heading_text", 15), ("supporting_text", 31)]], {}),
                    33: ("wagtail.blocks.ListBlock", (32,), {"min_num": 1}),
                    34: ("wagtail.blocks.StructBlock", [[("anchor_id", 7), ("feature_list_items", 33)]], {}),
                    35: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("section_header_block", 6),
                                ("figure_with_statistic_block", 11),
                                ("statistic_callout_block", 14),
                                ("features_with_modals", 30),
                                ("feature_list_block", 34),
                            ]
                        ],
                        {},
                    ),
                    36: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("link_to", 19),
                                ("page", 20),
                                ("file", 21),
                                ("custom_url", 22),
                                ("anchor", 23),
                                ("email", 24),
                                ("phone", 25),
                                ("new_window", 26),
                            ]
                        ],
                        {"label": "Link"},
                    ),
                    37: ("wagtail.blocks.StructBlock", [[("text", 4), ("link_text", 9), ("link", 36)]], {}),
                    38: ("wagtail.blocks.ListBlock", (37,), {"default": [], "label": "Call to Action", "max_num": 1, "min_num": 0}),
                    39: ("wagtail.blocks.StructBlock", [[("settings", 3), ("header", 6), ("content", 35), ("call_to_action", 38)]], {}),
                },
                null=True,
            ),
        ),
    ]
