# Generated by Django 5.2.9 on 2025-12-12 21:21

import django.db.models.deletion
from django.db import migrations, models

import wagtail.admin.forms.choosers
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("mozorg", "0021_alter_leadershippage_leadership_sections"),
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnonymIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "sections",
                    wagtail.fields.StreamField(
                        [("section", 21)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {"choices": [("", "---"), ("index", "Index"), ("top_glow", "Top Glow")], "inline_form": True, "required": False},
                            ),
                            1: ("wagtail.blocks.StructBlock", [[("theme", 0)]], {}),
                            2: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {"features": ["bold", "italic", "link", "superscript", "subscript", "strikethrough"], "required": False},
                            ),
                            3: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": ["bold", "italic", "link", "superscript", "subscript", "strikethrough"],
                                    "help_text": "Use Bold to make parts of this text black.",
                                },
                            ),
                            4: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {
                                    "default": False,
                                    "help_text": "The Default width is constrained to the layout grid with a max-width, centered on the page.",
                                    "inline_form": True,
                                    "label": "Make Full Width",
                                    "required": False,
                                },
                            ),
                            5: ("wagtail.blocks.StructBlock", [[("make_full_width", 4)]], {}),
                            6: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                            7: ("wagtail.blocks.StructBlock", [[("settings", 5), ("image", 6)]], {}),
                            8: ("wagtail.blocks.StreamBlock", [[("figure_block", 7)]], {}),
                            9: ("wagtail.blocks.CharBlock", (), {"label": "Link Text"}),
                            10: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("page", "Page"),
                                        ("file", "File"),
                                        ("custom_url", "Custom URL"),
                                        ("email", "Email"),
                                        ("anchor", "Anchor"),
                                        ("phone", "Phone"),
                                    ],
                                    "classname": "link_choice_type_selector",
                                    "label": "Link to",
                                    "required": False,
                                },
                            ),
                            11: ("wagtail.blocks.PageChooserBlock", (), {"form_classname": "page_link", "label": "Page", "required": False}),
                            12: (
                                "wagtail.documents.blocks.DocumentChooserBlock",
                                (),
                                {"form_classname": "file_link", "label": "File", "required": False},
                            ),
                            13: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "form_classname": "custom_url_link url_field",
                                    "label": "Custom URL",
                                    "max_length": 300,
                                    "required": False,
                                    "validators": [wagtail.admin.forms.choosers.URLOrAbsolutePathValidator()],
                                },
                            ),
                            14: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"form_classname": "anchor_link", "label": "#", "max_length": 300, "required": False},
                            ),
                            15: ("wagtail.blocks.EmailBlock", (), {"required": False}),
                            16: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"form_classname": "phone_link", "label": "Phone", "max_length": 30, "required": False},
                            ),
                            17: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {"form_classname": "new_window_toggle", "label": "Open in new window", "required": False},
                            ),
                            18: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("link_to", 10),
                                        ("page", 11),
                                        ("file", 12),
                                        ("custom_url", 13),
                                        ("anchor", 14),
                                        ("email", 15),
                                        ("phone", 16),
                                        ("new_window", 17),
                                    ]
                                ],
                                {},
                            ),
                            19: ("wagtail.blocks.StructBlock", [[("label", 9), ("link", 18)]], {}),
                            20: ("wagtail.blocks.ListBlock", (19,), {"default": [], "max_num": 1, "min_num": 0}),
                            21: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("settings", 1),
                                        ("superheading_text", 2),
                                        ("heading_text", 3),
                                        ("subheading_text", 2),
                                        ("content", 8),
                                        ("action", 20),
                                    ]
                                ],
                                {},
                            ),
                        },
                        null=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
