# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.9 on 2026-01-15 20:03

import django.db.models.deletion
from django.db import migrations, models

import wagtail.admin.forms.choosers
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("mozorg", "0021_alter_leadershippage_leadership_sections"),
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "donate",
                    wagtail.fields.StreamField(
                        [("donate_block", 17)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [("pink", "Pink"), ("green", "Green"), ("orange", "Orange"), ("gray", "Gray")],
                                    "help_text": "What color should the background be?",
                                    "required": False,
                                },
                            ),
                            1: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": (
                                        "Optional: Add an ID to make this section linkable. "
                                        "Will be converted to URL-safe format (e.g., 'Donate Section' becomes 'donate-section')."
                                    ),
                                    "max_length": 100,
                                    "required": False,
                                },
                            ),
                            2: ("wagtail.blocks.StructBlock", [[("background_color", 0), ("anchor_id", 1)]], {}),
                            3: ("wagtail.blocks.CharBlock", (), {"max_length": 255}),
                            4: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {"features": ["bold", "link"], "help_text": "Keep this to 2 paragraphs or fewer."},
                            ),
                            5: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {"help_text": "Ideal image size is 1400 x 700. Image will be cropped to a 2:1 aspect ratio."},
                            ),
                            6: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "A concise description of the image for someone who can't see it.",
                                    "max_length": 255,
                                    "required": False,
                                },
                            ),
                            7: ("wagtail.blocks.CharBlock", (), {"label": "Link text", "max_length": 50}),
                            8: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("page", "Page"),
                                        ("file", "File"),
                                        ("custom_url", "Custom URL"),
                                        ("email", "Email"),
                                        ("anchor", "Anchor"),
                                        ("phone", "Phone"),
                                    ],
                                    "classname": "link_choice_type_selector",
                                    "label": "Link to",
                                    "required": False,
                                },
                            ),
                            9: ("wagtail.blocks.PageChooserBlock", (), {"form_classname": "page_link", "label": "Page", "required": False}),
                            10: (
                                "wagtail.documents.blocks.DocumentChooserBlock",
                                (),
                                {"form_classname": "file_link", "label": "File", "required": False},
                            ),
                            11: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "form_classname": "custom_url_link url_field",
                                    "label": "Custom URL",
                                    "max_length": 300,
                                    "required": False,
                                    "validators": [wagtail.admin.forms.choosers.URLOrAbsolutePathValidator()],
                                },
                            ),
                            12: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"form_classname": "anchor_link", "label": "#", "max_length": 300, "required": False},
                            ),
                            13: ("wagtail.blocks.EmailBlock", (), {"required": False}),
                            14: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"form_classname": "phone_link", "label": "Phone", "max_length": 30, "required": False},
                            ),
                            15: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {"form_classname": "new_window_toggle", "label": "Open in new window", "required": False},
                            ),
                            16: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("link_to", 8),
                                        ("page", 9),
                                        ("file", 10),
                                        ("custom_url", 11),
                                        ("anchor", 12),
                                        ("email", 13),
                                        ("phone", 14),
                                        ("new_window", 15),
                                    ]
                                ],
                                {"label": "Link destination"},
                            ),
                            17: (
                                "wagtail.blocks.StructBlock",
                                [[("settings", 2), ("heading", 3), ("body", 4), ("image", 5), ("image_alt", 6), ("cta_text", 7), ("cta_link", 16)]],
                                {},
                            ),
                        },
                        help_text="The donate section of the homepage.",
                        null=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
