# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.9 on 2026-01-23 20:27

from django.db import migrations

import wagtail.admin.forms.choosers
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("mozorg", "0023_remove_homepage_donate_homepage_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="content",
            field=wagtail.fields.StreamField(
                [("donate_block", 20), ("gallery_block", 34), ("transition_block", 36)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional: Add an ID to make this section linkable (e.g., 'donate', 'support').",
                            "max_length": 100,
                            "required": False,
                        },
                    ),
                    1: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("", "White"),
                                ("m24-t-dark", "Dark"),
                                ("m24-t-green", "Green"),
                                ("m24-t-orange", "Orange"),
                                ("m24-t-pink", "Pink"),
                                ("m24-t-gray", "Gray"),
                            ],
                            "help_text": "What color should the background be?",
                            "required": False,
                        },
                    ),
                    2: ("wagtail.blocks.StructBlock", [[("anchor_id", 0), ("background_color", 1)]], {}),
                    3: ("bedrock.mozorg.blocks.common.DividerBlock", (), {"label": "Text"}),
                    4: ("wagtail.blocks.CharBlock", (), {"help_text": "Use sentence case.", "max_length": 255}),
                    5: ("wagtail.blocks.RichTextBlock", (), {"features": ["bold", "link"], "help_text": "Keep this to 2 paragraphs or fewer."}),
                    6: ("bedrock.mozorg.blocks.common.DividerBlock", (), {"label": "Image"}),
                    7: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"help_text": "Ideal image size is 1400 x 700. Image will be cropped to a 2:1 aspect ratio."},
                    ),
                    8: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": (
                                "A concise description of the image for someone who can't see it. "
                                "See <a href='https://mozmeao.github.io/platform-docs/cms/alt-text/' "
                                "target='_blank'>alt text guidelines</a> for tips."
                            ),
                            "max_length": 255,
                            "required": False,
                        },
                    ),
                    9: ("bedrock.mozorg.blocks.common.DividerBlock", (), {"label": "Call-to-action"}),
                    10: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Use sentence case (e.g., 'Donate', 'Read more').", "label": "Link text", "max_length": 50},
                    ),
                    11: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("page", "Page"),
                                ("file", "File"),
                                ("custom_url", "Custom URL"),
                                ("email", "Email"),
                                ("anchor", "Anchor"),
                                ("phone", "Phone"),
                            ],
                            "classname": "link_choice_type_selector",
                            "label": "Link to",
                            "required": False,
                        },
                    ),
                    12: ("wagtail.blocks.PageChooserBlock", (), {"form_classname": "page_link", "label": "Page", "required": False}),
                    13: ("wagtail.documents.blocks.DocumentChooserBlock", (), {"form_classname": "file_link", "label": "File", "required": False}),
                    14: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "form_classname": "custom_url_link url_field",
                            "label": "Custom URL",
                            "max_length": 300,
                            "required": False,
                            "validators": [wagtail.admin.forms.choosers.URLOrAbsolutePathValidator()],
                        },
                    ),
                    15: ("wagtail.blocks.CharBlock", (), {"form_classname": "anchor_link", "label": "#", "max_length": 300, "required": False}),
                    16: ("wagtail.blocks.EmailBlock", (), {"required": False}),
                    17: ("wagtail.blocks.CharBlock", (), {"form_classname": "phone_link", "label": "Phone", "max_length": 30, "required": False}),
                    18: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"form_classname": "new_window_toggle", "label": "Open in new window", "required": False},
                    ),
                    19: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("link_to", 11),
                                ("page", 12),
                                ("file", 13),
                                ("custom_url", 14),
                                ("anchor", 15),
                                ("email", 16),
                                ("phone", 17),
                                ("new_window", 18),
                            ]
                        ],
                        {"label": "Link destination"},
                    ),
                    20: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("settings", 2),
                                ("text_divider", 3),
                                ("heading", 4),
                                ("body", 5),
                                ("image_divider", 6),
                                ("image", 7),
                                ("image_alt", 8),
                                ("cta_divider", 9),
                                ("cta_text", 10),
                                ("cta_link", 19),
                            ]
                        ],
                        {},
                    ),
                    21: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional: Add an ID to make this section linkable (e.g., 'news', 'gallery').",
                            "max_length": 100,
                            "required": False,
                        },
                    ),
                    22: ("wagtail.blocks.StructBlock", [[("anchor_id", 21), ("background_color", 1)]], {}),
                    23: ("wagtail.blocks.CharBlock", (), {"max_length": 255, "required": False}),
                    24: ("wagtail.blocks.RichTextBlock", (), {"features": ["bold", "link"], "required": False}),
                    25: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("fifth", "Fifth (20%)"),
                                ("quarter", "Quarter (25%)"),
                                ("third", "Third (33%)"),
                                ("half", "Half (50%)"),
                                ("three-quarters", "Three-quarters (75%)"),
                            ],
                            "help_text": "Width of the tile in the gallery grid at desktop sizes.",
                        },
                    ),
                    26: ("bedrock.mozorg.blocks.common.DividerBlock", (), {"label": "Link"}),
                    27: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": (
                                "Upload a 2:1 aspect ratio image at 1400×700px - this is displayed "
                                "on mobile browsers. Wagtail will crop it for displaying at your "
                                "chosen aspect ratios for desktop."
                            ),
                        },
                    ),
                    28: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("2:1", "2:1 Wide landscape"),
                                ("1:1", "1:1 Square"),
                                ("5:4", "5:4 Landscape"),
                                ("4:5", "4:5 Portrait"),
                                ("2:3", "2:3 Tall portrait"),
                            ],
                            "help_text": "Aspect ratio for the image on desktop. The image will be cropped to fit.",
                        },
                    ),
                    29: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("", "None"),
                                ("community", "Community"),
                                ("event", "Event"),
                                ("impact", "Impact"),
                                ("partnership", "Partnership"),
                                ("policy", "Policy"),
                                ("product", "Product"),
                                ("program", "Program"),
                                ("project", "Project"),
                                ("research", "Research"),
                            ],
                            "required": False,
                        },
                    ),
                    30: ("wagtail.blocks.TextBlock", (), {"help_text": "Short blurb about what you're linking to.", "required": False}),
                    31: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Use sentence case (e.g., 'Read more', 'Watch now').",
                            "label": "Call to action text (optional)",
                            "max_length": 100,
                            "required": False,
                        },
                    ),
                    32: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("width", 25),
                                ("link_divider", 26),
                                ("cta_link", 19),
                                ("image_divider", 6),
                                ("image", 27),
                                ("image_ratio", 28),
                                ("image_alt", 8),
                                ("text_divider", 3),
                                ("tag", 29),
                                ("heading", 4),
                                ("body", 30),
                                ("cta_text", 31),
                            ]
                        ],
                        {},
                    ),
                    33: (
                        "wagtail.blocks.ListBlock",
                        (32,),
                        {"help_text": "Add gallery tiles. For best results, ensure tile widths add up to 100% per row.", "min_num": 1},
                    ),
                    34: ("wagtail.blocks.StructBlock", [[("settings", 22), ("heading", 23), ("intro", 24), ("tiles", 33)]], {}),
                    35: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("light", "White"),
                                ("dark", "Dark"),
                                ("green", "Green"),
                                ("orange", "Orange"),
                                ("pink", "Pink"),
                                ("gray", "Gray"),
                            ]
                        },
                    ),
                    36: ("wagtail.blocks.StructBlock", [[("top_color", 35), ("bottom_color", 35)]], {}),
                },
                help_text="Add content blocks for the homepage. Blocks will render in the order shown.",
                null=True,
            ),
        ),
    ]
