# Generated by Django 5.2.9 on 2026-01-27 16:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("advertising", "0001_initial"),  # Advertising migration must run first
        ("mozorg", "0024_alter_homepage_content"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name="advertisingtwocolumnsubpage",
                    name="page_ptr",
                ),
                migrations.RemoveField(
                    model_name="contentsubpage",
                    name="contact_banner",
                ),
                migrations.RemoveField(
                    model_name="contentsubpage",
                    name="notification",
                ),
                migrations.RemoveField(
                    model_name="contentsubpage",
                    name="page_ptr",
                ),
                migrations.DeleteModel(
                    name="AdvertisingIndexPage",
                ),
                migrations.DeleteModel(
                    name="AdvertisingTwoColumnSubpage",
                ),
                migrations.DeleteModel(
                    name="ContentSubpage",
                ),
            ],
            database_operations=[],  # Empty - we don't touch the database, tables stay as-is
        ),
    ]
