# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.12 on 2026-03-24 21:36

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mozorg", "0025_alter_homepage_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationsnippet",
            name="notification_text",
            field=wagtail.fields.RichTextField(),
        ),
    ]
