# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.12 on 2026-04-16 19:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mozorg", "0028_alter_advertisingindexpage_sub_navigation"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationsnippet",
            name="analytics_id",
            field=models.CharField(
                blank=True, help_text="Unique identifier for analytics tracking of social links in this notification.", max_length=36
            ),
        ),
    ]
