# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.14 on 2026-06-09 19:54

import django.db.models.deletion
import uuid
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_create_alias_locale_records'),
        ('mozorg', '0032_alter_aboutuspage_content_alter_homepage_content'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadershipProfileSnippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation_key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=255)),
                ('press_photos_link', models.URLField(blank=True, help_text='External link to a .zip file of photos of the person.')),
                ('biography', wagtail.fields.RichTextField(blank=True, help_text='A biography limited to a few short paragraphs. Links and formatting are supported.')),
                ('external_links', wagtail.fields.StreamField([('external_link', 3)], blank=True, block_lookup={0: ('wagtail.blocks.URLBlock', (), {'char_max_length': 255, 'help_text': "Link to the person's website or social media account.", 'required': False}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('url mastodon', 'Mastodon'), ('url twitter', 'Twitter'), ('url website', 'Website')], 'help_text': 'Selects a visual icon type for the link.', 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'char_max_length': 255, 'help_text': 'Text to display for the link.', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('url', 0), ('type', 1), ('text', 2)]], {})}, null=True)),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cms.bedrockimage')),
                ('locale', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale', verbose_name='locale')),
            ],
            options={
                'verbose_name': 'Leadership Profile',
                'verbose_name_plural': 'Leadership Profiles',
                'abstract': False,
                'unique_together': {('translation_key', 'locale')},
            },
        ),
    ]
