# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.9 on 2026-01-14 22:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("anonym", "0002_update_anonym_pages_to_new_contenttypes"),
        ("mozorg", "0033_remove_anonymcontactpage_page_ptr_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name="Person",
                ),
            ],
            database_operations=[],
        ),
    ]
