# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.14 on 2026-06-09 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mozorg', '0034_populate_leadership_profile_snippets'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leadershipprofilesnippet',
            options={'ordering': ['name'], 'verbose_name': 'Leadership Profile', 'verbose_name_plural': 'Leadership Profiles'},
        ),
    ]
