# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.9 on 2026-01-13 20:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("anonym", "0001_initial"),
        ("mozorg", "0035_alter_anonymarticlepage_content_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name="anonymcontactpage",
                    name="page_ptr",
                ),
                migrations.RemoveField(
                    model_name="anonymcontentsubpage",
                    name="page_ptr",
                ),
                migrations.RemoveField(
                    model_name="anonymindexpage",
                    name="page_ptr",
                ),
                migrations.RemoveField(
                    model_name="anonymnewspage",
                    name="page_ptr",
                ),
                migrations.RemoveField(
                    model_name="anonymtopandbottompage",
                    name="page_ptr",
                ),
                migrations.DeleteModel(
                    name="AnonymArticlePage",
                ),
                migrations.DeleteModel(
                    name="AnonymContactPage",
                ),
                migrations.DeleteModel(
                    name="AnonymContentSubPage",
                ),
                migrations.DeleteModel(
                    name="AnonymIndexPage",
                ),
                migrations.DeleteModel(
                    name="AnonymNewsPage",
                ),
                migrations.DeleteModel(
                    name="AnonymTopAndBottomPage",
                ),
            ],
            database_operations=[],
        ),
    ]
