# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.14 on 2026-06-10 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_create_alias_locale_records'),
        ('mozorg', '0036_organizationleadershipindexpage_organizationleadershipsubpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadershipprofilesnippet',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cms.bedrockimage'),
        ),
    ]
