# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.14 on 2026-06-16 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mozorg', '0039_migrate_showcase_two_column_layout'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationleadershipindexpage',
            name='sub_pages_link_description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
