# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.14 on 2026-06-22 19:06

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mozorg', '0041_organizationleadershipindexpage_exec_closing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationleadershipsubpage',
            name='leadership_groups',
            field=wagtail.fields.StreamField([('group', 7)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'char_max_length': 255, 'help_text': "Leadership group title, e.g. 'Executive Steering Committee' or 'Senior Leadership'.", 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'char_max_length': 1000, 'help_text': 'A couple of sentences describing what the group is and some helpful context.', 'required': False}), 2: ('wagtail.snippets.blocks.SnippetChooserBlock', ('mozorg.LeadershipProfileSnippet',), {}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'Job title to display for this placement. Leave blank to omit.', 'max_length': 255, 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('profile', 2), ('job_title', 3)]], {}), 5: ('wagtail.blocks.ListBlock', (4,), {'min_num': 1}), 6: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'hr', 'bold', 'italic', 'code', 'blockquote', 'superscript', 'link', 'ol', 'ul', 'image'], 'help_text': 'Optional closing text displayed after the list of leaders.', 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1), ('leaders', 5), ('closing', 6)]], {})}),
        ),
    ]
