# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.16 on 2026-10-06 04:04

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mozorg', '0053_pullquote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='content',
            field=wagtail.fields.StreamField([('text', 0), ('image_caption', 5), ('pullquote_block', 11)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'lede', 'hr', 'bold', 'italic', 'code', 'blockquote', 'superscript', 'link', 'ol', 'ul'], 'icon': 'pilcrow', 'label': 'Text', 'template': 'mozorg/cms/blocks/longform_block.html'}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': "A concise description of the image for someone who can't see it. See <a href='https://mozmeao.github.io/platform-docs/cms/alt-text/' target='_blank'>alt text guidelines</a> for tips.", 'max_length': 255, 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('image', 1), ('image_alt', 2)]], {}), 4: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'help_text': 'Optional caption shown below the image.', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 3), ('caption', 4)]], {}), 6: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('', 'White'), ('m24-t-dark', 'Dark'), ('m24-t-green', 'Green'), ('m24-t-orange', 'Orange'), ('m24-t-pink', 'Pink'), ('m24-t-gray', 'Gray')], 'help_text': 'What color should the background be?', 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('background_color', 6)]], {}), 8: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link']}), 9: ('wagtail.blocks.CharBlock', (), {'help_text': 'Name of the person being quoted.', 'max_length': 255, 'required': False}), 10: ('wagtail.blocks.RichTextBlock', (), {'features': ['italic', 'link', 'bold'], 'help_text': "Flexible extra field for more information (author's title, name and/or link to the source, date, etc.)", 'required': False}), 11: ('wagtail.blocks.StructBlock', [[('settings', 7), ('quote', 8), ('author', 9), ('citation', 10)]], {})}, help_text='Add the body of the article. Blocks will render in the order shown.', null=True),
        ),
    ]
