ARG FROM_TAG
FROM ${FROM_TAG}

CMD ["./bin/run-tests.sh"]
USER root

RUN pip install --no-cache-dir -r requirements/test.txt
COPY ./setup.cfg ./
COPY ./tests ./tests

RUN chown webdev.webdev -R .
USER webdev
