[tool.ruff]
# Set what ruff should check for.
# See https://beta.ruff.rs/docs/rules/ for a list of rules.
select = [
    # TODO: Enable flake8-builtin and fix errors to fix variable name shadowing errors.
    # "A", # flake8-builtin errors.
    # TODO: Enable bugbear and fix errors.
    # "B", # bugbear errors
    "DJ", # flake8-django errors.
    "E", # pycodestyle errors
    "F", # pyflakes errors
    "I", # import sorting
    "Q", # flake8-quotes errors
    "W", # pycodestyle warnings
]
line-length = 150  # To match flake8
target-version = 'py39'
extend-exclude = ["__pycache__", "docs", "assets", "static", "bedrock/externalfiles/files_cache"]

[tool.ruff.per-file-ignores]
"bedrock/settings/__init__.py" = ["F405"]
"bedrock/contentful/tests/data.py" = ["E501"]

[tool.ruff.isort]
known-first-party = ["bedrock", "lib", "pages"]
section-order = ["future", "standard-library", "django", "third-party", "first-party", "local-folder"]
combine-as-imports = true

[tool.ruff.isort.sections]
django = ["django"]
