[tool.black]
line-length = 150  # To match flake8
target-version = ['py37']
include = '\.pyi?$'
exclude = '''
/(
	.+/migrations
)
'''

[tool.isort]
combine_as_imports = true
default_section = 'THIRDPARTY'
include_trailing_comma = true
known_django = 'django'
known_first_party = 'bedrock,lib,pages'
profile = 'black'
sections = 'FUTURE,STDLIB,DJANGO,THIRDPARTY,FIRSTPARTY,LOCALFOLDER'