# Generated by Django 2.2.8 on 2020-01-22 17:57

import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0005_mitrecve_mfsa_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='halloffamer',
            name='program',
            field=models.CharField(choices=[('web', 'Web'), ('client', 'Client')], max_length=10),
        ),
        migrations.AlterField(
            model_name='securityadvisory',
            name='last_modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True),
        ),
    ]
