# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 4.2.11 on 2024-05-08 20:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("security", "0007_alter_mitrecve_order_alter_mitrecve_year_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mitrecve",
            name="reporter",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="securityadvisory",
            name="reporter",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
