# Generated by Django 4.2.16 on 2024-10-21 20:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pocketfeed", "0002_auto_20180723_0805"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PocketArticle",
        ),
    ]
