# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

### URL: https://www-dev.allizom.org/firefox/browsers/compare/chrome/

# HTML page title
compare-chrome-firefox-vs-chrome-which-is = { -brand-name-firefox } vs. { -brand-name-chrome }: Which is better?

# HTML page description
compare-chrome-we-compare-mozilla-firefox = We compare { -brand-name-mozilla } { -brand-name-firefox } with { -brand-name-google } { -brand-name-chrome } in terms of privacy, utility and portability

# Main title.
compare-chrome-comparing-firefox-browser = Comparing { -brand-name-firefox-browser } with { -brand-name-google } { -brand-name-chrome }

# Variables:
#   $attrs (string) - link to https://monitor.firefox.com with additional attributes for analytics
compare-chrome-at-firefox-we-have-a-huge = At { -brand-name-firefox }, we have a huge number of dedicated users who appreciate our steadfast dedication to online privacy. For example, the latest version of { -brand-name-firefox } includes a feature called Enhanced Tracking Protection (ETP) which is turned on by default for all users worldwide. ETP blocks over 2,000 trackers, including social trackers from companies like { -brand-name-facebook }, { -brand-name-twitter }, and LinkedIn. It also has an integrated feature called <a { $attrs }>{ -brand-name-firefox-monitor }</a> that automatically notifies you if your password has been breached or needs to be updated. In addition to these protections, Private Browsing mode in { -brand-name-firefox } automatically deletes your browsing information such as history and cookies, leaving no trace after you finish your session.

# Variables:
#   $attrs (string) - link to https://monitor.firefox.com with additional attributes for analytics
compare-chrome-at-firefox-we-have-a-huge-fallback = At { -brand-name-firefox }, we have a huge number of dedicated users who appreciate our steadfast dedication to online privacy. For example, the latest version of { -brand-name-firefox } includes a feature called Enhanced Tracking Protection (ETP) which is turned on by default for all users worldwide. ETP blocks over 2,000 trackers, including social trackers from companies like { -brand-name-facebook }, { -brand-name-twitter }, and LinkedIn. It also has an integrated feature called <a { $attrs }>{ -brand-name-firefox-monitor }</a> that automatically notifies you if your password has been breached or needs to be updated. In addition to these protections, { -brand-name-firefox }'s Private Browsing mode automatically deletes your browsing information such as history and cookies, leaving no trace after you finish your session.

# Variables:
#   $attrs (string) - link to mozilla.org/privacy/firefox/ with additional attributes for analytics
compare-chrome-weve-also-recently-restated = We’ve also recently restated our commitment to privacy and transparency regarding user data in our most recent <a { $attrs }>Privacy Notice</a> that states, “At Mozilla, we believe that privacy is fundamental to a healthy internet.”
compare-chrome-google-chrome-is-by-all-accounts = { -brand-name-google } { -brand-name-chrome } is by all accounts a secure browser, with features like { -brand-name-google } Safe Browsing, which helps protect users by displaying an impossible-to-miss warning when they attempt to navigate to dangerous sites or download dangerous files.

# To "draw the line" is to establish a boundary that should not be crossed. Alternative: "it's up to you to decide whether or not or where your limit is with sharing things (...)".
compare-chrome-ultimately-its-up-to-you = Ultimately, it’s up to you to decide whether or not or where to draw the line with sharing things like your search history and shopping history. But if you’re anything like most people, you’ve probably searched for some things on the internet that you would rather keep private.

# "we've been heads down" means we've been hard at work. Alternative: "we've been hard at work." "Heads down" is when someone is looking down to avoid distractions and focus on the immediate task in front of them.
compare-chrome-fast-forward-to-today-the = Fast-forward to today, the competitive landscape for browsers has changed with many people beginning to question just what is happening to their online data such as browsing history, passwords, and other sensitive information. A lot has changed since 2008 when { -brand-name-chrome } came onto the scene. At { -brand-name-firefox }, we’ve been heads down, working to redesign our interface and provide users with an ever growing number of privacy and performance enhancements as well as plenty of handy browser tools.
compare-chrome-and-so-here-we-are-the-browser = And so here we are, the browser-wars are escalating once again and it’s time to reevaluate and compare { -brand-name-firefox-browser } vs { -brand-name-google } { -brand-name-chrome }.
compare-chrome-in-2008-google-introduced = In 2008, { -brand-name-google } introduced { -brand-name-chrome }, and its impact as an innovation in browser technology was immediate. It was faster for loading sites, took up minimal screen space and offered an undeniably simple user interface.
compare-chrome-in-fact-both-chrome-and-firefox = In fact, both { -brand-name-chrome } and { -brand-name-firefox } have rigorous security in place. Both include a thing called “sandboxing” which separates the processes of the browser so something like a harmful website doesn’t infect other parts of your laptop or other device.

# "Beside the point" means that a subject might be worth noting, but isn't the main focus (the point) of the discussion. Alternative: "but that's not the real issue."
compare-chrome-while-chrome-proves-to-be = While { -brand-name-chrome } proves to be a safe web browser, its privacy record is questionable. { -brand-name-google } actually collects a disturbingly large amount of data from its users including location, search history and site visits. { -brand-name-google } makes its case for data collection saying it’s doing it to improve its services – like helping you find a sweater or a coffee shop like the one you previously bought or visited. However, others might disagree, making the point that { -brand-name-google } is actually gathering an unprecedented amount of data for its own marketing purposes. They tout that they’re keeping your information private from hackers, but that’s beside the point. { -brand-name-google } itself runs the world’s largest advertising network, thanks in large part to data they harvest from their users.

# "Gmail" and "Google Docs" are brand names.
compare-chrome-in-terms-of-features-both = In terms of features, both { -brand-name-firefox } and { -brand-name-chrome } offer a large library of extensions and plug-ins, with { -brand-name-chrome }’s catalog vastly outnumbering any other browser while nicely integrating with other { -brand-name-google } services, like Gmail and { -brand-name-google } Docs.
compare-chrome-firefox-also-has-a-sync-feature = { -brand-name-firefox } also has a sync feature to see your open and recent tabs, browsing history, and bookmarks across all your devices.
compare-chrome-while-chrome-gets-the-nod = While { -brand-name-chrome } gets the nod with add-ons and extensions, { -brand-name-firefox } has a nicely curated set of built-in features, such as the incredibly handy screen capture tool, and reading mode feature which strips away everything from the page except the text from the article you’re reading.
compare-chrome-although-not-as-extensive = Although not as extensive as { -brand-name-chrome }’s add-on library, { -brand-name-firefox }, as open-source software with a huge number of active contributors, also features an incredible number of useful extensions.
compare-chrome-if-having-tons-of-open-tabs = If having tons of open tabs is your thing, then it really comes down to your UI preference. { -brand-name-firefox } features a horizontal scroll on all your open tabs rather than shrinking them smaller and smaller with each new one. { -brand-name-google } { -brand-name-chrome } prefers to shrink them down so just the favicon is visible. The only problem with this is when you have multiple tabs open from the same website, so you see the same favicon across your tabs.
compare-chrome-almost-needless-to-say-versions = Almost needless to say, versions of both { -brand-name-firefox } and { -brand-name-chrome } are available for the most popular desktop and mobile operating systems ({ -brand-name-windows }, { -brand-name-mac }, { -brand-name-linux }, { -brand-name-android }, { -brand-name-ios }).
compare-chrome-both-chrome-and-firefox-also = Both { -brand-name-chrome } and { -brand-name-firefox } also allow you to sync things like passwords, bookmarks, and open tabs across all your devices. If you have a { -brand-name-firefox } account, you can manually send an open tab on your desktop to your mobile device or vice versa. With { -brand-name-chrome }, it’s done automatically if you’ve chosen that setting in your preferences. Not having to manually send the tab from one device to the other is convenient when you want to do something like continue reading an article you didn’t finish earlier. But there could be times where automatic syncing might not be ideal if there’s a chance multiple users are browsing while signed in to your { -brand-name-google } account.

# "Neck and neck" means they are evenly matched. Alternative: "evenly matched". "Baked-in" means it's included, not added in later. Alternatives: "built-in" or "included".
compare-chrome-we-think-its-fair-to-say = We think it’s fair to say { -brand-name-firefox } and { -brand-name-chrome } are really neck and neck in terms of portability and utility, with { -brand-name-chrome } having a slight edge in utility because of its huge library of extensions and add-on features. But in terms of Privacy, { -brand-name-firefox } wins the day with our commitment to preserving our users’ online data and providing free baked-in services like password managers that also alert you if there happens to be a data breach involving your credentials.
compare-chrome-as-for-customization-our = As for customization, our fans will tell you one of the things they love most about our browser is its ability to allow you to move and arrange a majority of the UI elements to best suit your needs. { -brand-name-chrome } allows you to hide certain UI elements but there’s not much allowance, if any, for moving things around based on your preferences. However, it should be noted that both { -brand-name-chrome } and { -brand-name-firefox } make it pretty easy to change your browser’s appearance and theme.
compare-chrome-for-practical-purposes-theres = For practical purposes, there’s obviously really nothing preventing you from using both browsers—{ -brand-name-firefox } for those moments in life when privacy really matters, and { -brand-name-chrome } if you’re still invested in the { -brand-name-google } ecosystem. Yet with the growing number of incursions into our personal data, { -brand-name-firefox } may prove to be the right choice in the long run for those of us who value protecting our personal privacy online.
