# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

### URL: https://www-dev.allizom.org/firefox/browsers/compare/

# HTML page title, also used for the main title
compare-index-seven-of-the-best-browsers-in = Seven of the best browsers in direct comparison
compare-index-six-of-the-best-browsers-fallback = Six of the best browsers in direct comparison

# Sub-headline
compare-index-privacy-utility-portability = Privacy. Utility. Portability.

# HTML page description
compare-index-a-great-internet-browser-should = A great internet browser should have the functionality you need, portability across devices, and the privacy you deserve.
compare-index-which-browser-is-best-at-keeping = Which browser is best at keeping things confidential?
compare-index-its-not-unreasonable-to-expect = It’s not unreasonable to expect a high level of data protection and privacy from the products we regularly use to get online. At a minimum, a browser should offer some version of “private browsing mode” that automatically deletes your history and search history so other users on the same computer can’t access it. In this area, all seven of the browsers compared here score points.
compare-index-its-not-unreasonable-to-expect-fallback = It’s not unreasonable to expect a high level of data protection and privacy from the products we regularly use to get online. At a minimum, a browser should offer some version of “private browsing mode” that automatically deletes your history and search history so other users on the same computer can’t access it. In this area, all six of the browsers compared here score points.
compare-index-what-you-do-online-literally = What you do online literally shouldn’t be anyone else’s business.
compare-index-another-browser-feature-that = Another browser feature that should be a given is the ability to prevent websites and companies from tracking your browsing and shopping data — even in normal browsing mode.
compare-index-another-browser-feature-fallback = Another browser feature that should be a given is the ability to prevent websites and companies from tracking your browsing and shopping data — even in normal browsing mode. But that’s actually not the case: in fact, the only browsers that block third party tracking cookies by default are { -brand-name-firefox } and { -brand-name-safari }.
compare-index-using-a-browser-that-blocks = Using a browser that blocks third-party trackers isn’t just important for privacy — it usually means it runs much faster, too. Most trackers are just scripts that run in the background on a number of websites. You can’t see them, but you can feel them slowing down your browser. As of version 67 of { -brand-name-firefox }, fingerprinting and cryptominers are also blocked. If you’re not familiar with cryptominers, here’s an example of how they can affect you: maybe you’ve experienced your computer suddenly running hotter or the battery depleting faster than normal. That’s often the byproduct of cryptominers creeping around on your device.
compare-index-what-has-your-browser-done = What has your browser done for you lately?
compare-index-in-addition-to-privacy-protection = In addition to privacy protection, which largely takes place in the background of the browser, another key ingredient to a well-made browser is the actual user interface and functionality. Almost all seven browsers are equal when it comes to tab browsing, bookmark management, auto-completion, proofreading and extensions. { -brand-name-firefox }, { -brand-name-edge } and { -brand-name-opera } also offer a quick screenshot function that proves to be quite handy and is definitely something you notice is missing when you switch over to a browser without it.
compare-index-in-addition-to-privacy-protection-fallback = In addition to privacy protection, which largely takes place in the background of the browser, another key ingredient to a well-made browser is the actual user interface and functionality. Almost all six browsers are equal when it comes to tab browsing, bookmark management, auto-completion, proofreading and extensions. { -brand-name-firefox }, { -brand-name-edge } and { -brand-name-opera } also offer a quick screenshot function that proves to be quite handy and is definitely something you notice is missing when you switch over to a browser without it.
compare-index-how-well-does-your-browser = How well does your browser work across your devices?
compare-index-almost-all-of-the-browsers = Almost all of the browsers compared here allow synchronization between desktop and mobile devices. You’ll need an account to do it, which you can use to log into the browser on all devices and synchronize things like passwords, browsing history, bookmarks and settings.
compare-index-conclusion = Conclusion:
compare-index-and-the-winner-is = And the winner is…
compare-index-find-out-how-firefox-chrome = Find out how { -brand-name-firefox }, { -brand-name-chrome }, { -brand-name-edge }, { -brand-name-safari }, { -brand-name-opera }, { -brand-name-brave } and { -brand-name-ie } differ in terms of privacy, utility and portability.
compare-index-find-out-how-firefox-fallback = Find out how { -brand-name-firefox }, { -brand-name-chrome }, { -brand-name-edge }, { -brand-name-safari }, { -brand-name-opera } and { -brand-name-ie } differ in terms of privacy, utility and portability.
compare-index-looking-for-a-better-browser = Looking for a better browser? We’ll compare { -brand-name-firefox } with { -brand-name-chrome }, { -brand-name-edge }, { -brand-name-safari }, { -brand-name-opera }, { -brand-name-brave } and { -brand-name-ie } to help you make your decision.
compare-index-looking-for-a-better-fallback = Looking for a better browser? We’ll compare { -brand-name-firefox } with { -brand-name-chrome }, { -brand-name-edge }, { -brand-name-safari }, { -brand-name-opera } and { -brand-name-ie } to help you make your decision.
compare-index-so-is-your-browser-the-best = So is your browser the best one for what you do online? The right browser can make a big difference in how you experience the web. So, without further ado, let’s compare { -brand-name-google } { -brand-name-chrome }, { -brand-name-firefox }, { -brand-name-safari }, { -brand-name-opera }, { -brand-name-brave }, { -brand-name-microsoft } { -brand-name-ie } and { -brand-name-edge } — and see which best suits your needs.
compare-index-so-is-your-browser-the-fallback = So is your browser the best one for what you do online? The right browser can make a big difference in how you experience the web. So, without further ado, let’s compare { -brand-name-google } { -brand-name-chrome }, { -brand-name-firefox }, { -brand-name-safari }, { -brand-name-opera }, { -brand-name-microsoft } { -brand-name-ie } and { -brand-name-edge } — and see which best suits your needs.
compare-index-since-your-browser-is-your = Since your browser is your gateway to the internet, speed, security, privacy and utility are paramount. In recent years, { -brand-name-google } { -brand-name-chrome } has been the browser of choice for many. But at a time when online ads seem to follow us everywhere and data breaches are a fixture of news headlines, a lot of people are starting to demand more privacy and respect from their browser.
compare-index-the-first-thing-to-point-out = The first thing to point out about portability is that not all browsers run on all operating systems. While { -brand-name-firefox }, { -brand-name-chrome }, { -brand-name-edge }, { -brand-name-brave } and { -brand-name-opera } work on all major systems and are easy to install, { -brand-name-ie } and { -brand-name-safari } only work on { -brand-name-microsoft } and Apple’s own systems. The mobile version of { -brand-name-safari } is pre-installed on Apple’s mobile devices, and most { -brand-name-android } devices come with a pre-installed browser modified by the manufacturer for the device. { -brand-name-firefox }, { -brand-name-chrome }, { -brand-name-brave }, { -brand-name-edge } and { -brand-name-opera } can easily be installed and even used side by side.
compare-index-the-first-thing-to-point-fallback = The first thing to point out about portability is that not all browsers run on all operating systems. While { -brand-name-firefox }, { -brand-name-chrome } and { -brand-name-opera } work on all major systems and are easy to install, { -brand-name-ie }, { -brand-name-edge } and { -brand-name-safari } only work on { -brand-name-microsoft } and Apple’s own systems. The mobile version of { -brand-name-safari } is pre-installed on Apple’s mobile devices, and most { -brand-name-android } devices come with a pre-installed browser modified by the manufacturer for the device. { -brand-name-firefox }, { -brand-name-chrome }, { -brand-name-edge } and { -brand-name-opera } can easily be installed and even used side by side.
compare-index-browsers-have-come-a-long = Browsers have come a long way since { -brand-name-chrome } was introduced and took over the market share. Most of the modern browsers have closed the gap on portability and functionality, and in some areas, like speed and privacy, have actually surpassed { -brand-name-chrome }. Still, determining which browser is right for you will always depend on your individual needs and what you value most as you navigate online.
compare-index-firefox-is-backed-by-the-not = { -brand-name-firefox } is backed by the not-for-profit { -brand-name-mozilla }.
compare-index-firefox-puts-your-privacy = { -brand-name-firefox } puts your privacy first — in everything we make and do. We believe you have the right to decide how and with whom you share your personal information. { -brand-name-firefox } collects as little data as possible and never sells it. The little data we do collect is only used to make products and features better. No secrets. But a lot of transparency and real privacy.
compare-index-based-on-the-criteria-we-outlined = Based on the criteria we outlined — privacy, utility, and portability — there’s really only one browser that meets the mark, and that’s { -brand-name-firefox }. The real area of difference isn’t in functionality, it’s privacy. { -brand-name-firefox } is the most private browser that doesn’t lock you into an ecosystem. Use it on any operating system, on all your devices, and feel secure when you do.
