version: "3"
services:
  selenium-hub:
    image: selenium/hub:3
  chrome:
    image: selenium/node-chrome:3.141.59-20210713
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    links:
      - selenium-hub:selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      - SE_NODE_SESSION_TIMEOUT=600

  firefox:
    image: selenium/node-firefox:3
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    links:
      - selenium-hub:selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      - SE_NODE_SESSION_TIMEOUT=600
