# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 3.2.21 on 2023-09-26 17:50

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Breach",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("domain", models.CharField(max_length=255)),
                ("breach_date", models.DateField(null=True)),
                ("added_date", models.DateTimeField(null=True)),
                ("modified_date", models.DateTimeField(null=True)),
                ("pwn_count", models.PositiveIntegerField(default=0)),
                ("logo_path", models.CharField(max_length=255)),
                ("data_classes", models.JSONField(default=list)),
                ("is_verified", models.BooleanField(default=False)),
                ("is_fabricated", models.BooleanField(default=False)),
                ("is_sensitive", models.BooleanField(default=False)),
                ("is_retired", models.BooleanField(default=False)),
                ("is_spam_list", models.BooleanField(default=False)),
                ("is_malware", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name_plural": "Breaches",
            },
        ),
    ]
