# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 4.2.16 on 2024-10-15 12:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_vpncalltoactionsnippet_locale_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vpncalltoactionsnippet",
            options={
                "verbose_name": "VPN Call To Action Snippet",
                "verbose_name_plural": "VPN Call To Action Snippets",
            },
        ),
    ]
