# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 4.2.17 on 2025-01-30 23:10

from django.db import migrations, models
import django.db.models.deletion
import uuid
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailcore", "0093_uploadedfile"),
        ("cms", "0002_bedrockimage_bedrockrendition"),
        ("products", "0003_alter_vpncalltoactionsnippet_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="MonitorCallToActionSnippet",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("translation_key", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("split_heading", models.CharField(max_length=255, null=True)),
                ("split_subheading", models.CharField(max_length=255, null=True)),
                ("split_content", wagtail.fields.RichTextField(blank=True)),
                ("split_button_text", models.CharField(max_length=255, null=True, verbose_name="Link Text")),
                ("split_button_link", models.URLField(null=True, verbose_name="Link URL")),
                ("locale", models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name="+", to="wagtailcore.locale")),
                (
                    "split_image",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="cms.bedrockimage"),
                ),
            ],
            options={
                "verbose_name": "Monitor Call To Action Snippet",
                "verbose_name_plural": "Monitor Call To Action Snippets",
                "abstract": False,
                "unique_together": {("translation_key", "locale")},
            },
        ),
        migrations.CreateModel(
            name="MonitorArticleIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("split_heading", models.CharField(max_length=255, null=True)),
                ("split_subheading", models.CharField(blank=True, max_length=255, null=True)),
                ("split_content", wagtail.fields.RichTextField(blank=True, null=True)),
                ("split_button_text", models.CharField(max_length=255, null=True)),
                ("split_button_link", models.URLField(null=True)),
                ("articles_heading", models.CharField(max_length=255, null=True)),
                ("articles_subheading", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "call_to_action_bottom",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="products.monitorcalltoactionsnippet",
                    ),
                ),
                ("split_image", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="cms.bedrockimage")),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="MonitorArticleDetailPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "icon",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="cms.bedrockimage"),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
