# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 4.2.18 on 2025-01-31 19:43

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0005_monitorarticledetailpage_call_to_action_bottom_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="monitorarticledetailpage",
            name="content",
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
    ]
