# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 4.2.20 on 2025-03-27 17:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0005_monitorcalltoactionsnippet_monitorarticlepage_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="monitorarticleindexpage",
            name="articles_heading",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="monitorarticleindexpage",
            name="split_button_text",
            field=models.CharField(max_length=255, verbose_name="Link Text"),
        ),
        migrations.AlterField(
            model_name="monitorarticleindexpage",
            name="split_heading",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="monitorarticleindexpage",
            name="split_subheading",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="monitorcalltoactionsnippet",
            name="split_button_text",
            field=models.CharField(max_length=255, verbose_name="Link Text"),
        ),
        migrations.AlterField(
            model_name="monitorcalltoactionsnippet",
            name="split_heading",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="monitorcalltoactionsnippet",
            name="split_subheading",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
