# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 4.2.18 on 2025-01-31 20:46

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0006_monitorarticledetailpage_content"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="monitorarticledetailpage",
            name="heading",
        ),
        migrations.AddField(
            model_name="monitorarticledetailpage",
            name="body",
            field=wagtail.fields.StreamField([("text", wagtail.blocks.RichTextBlock())], blank=True, null=True),
        ),
    ]
