# Generated by Django 5.2.2 on 2025-07-16 19:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0006_alter_monitorarticleindexpage_articles_heading_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="monitorarticlepage",
            name="icon",
        ),
    ]
