# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.2 on 2025-07-16 19:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0006_alter_monitorarticleindexpage_articles_heading_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="monitorarticlepage",
            name="icon",
        ),
    ]
