# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 2.2.24 on 2021-11-23 00:09

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Position",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("job_id", models.CharField(max_length=10)),
                ("title", models.CharField(max_length=100)),
                ("department", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=500)),
                ("job_locations", models.CharField(default="", max_length=500)),
                ("is_mofo", models.BooleanField(default=False)),
                ("description", models.TextField()),
                ("apply_url", models.URLField()),
                ("source", models.CharField(max_length=100)),
                ("position_type", models.CharField(max_length=100)),
                ("updated_at", models.DateTimeField(default=datetime.datetime.utcnow)),
            ],
            options={
                "ordering": ("department", "title"),
            },
        ),
    ]
