# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.14 on 2026-09-08 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0003_alter_position_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='internal_job_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='job_id',
            field=models.CharField(max_length=36),
        ),
    ]
