# Generated by Django 2.2.21 on 2021-08-30 18:38

from django.db import migrations, models
import django.utils.timezone
import django_extensions.db.fields.json


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentfulEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contentful_id', models.CharField(max_length=20, unique=True)),
                ('content_type', models.CharField(max_length=20)),
                ('language', models.CharField(max_length=5)),
                ('last_modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('url_base', models.CharField(blank=True, max_length=255)),
                ('slug', models.CharField(blank=True, max_length=255)),
                ('data_hash', models.CharField(max_length=64)),
                ('data', django_extensions.db.fields.json.JSONField(default=dict)),
            ],
        ),
    ]
