# Generated by Django 2.2.20 on 2021-06-04 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentful', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentfulentry',
            name='slug',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='contentfulentry',
            name='url_base',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='contentfulentry',
            unique_together={('content_type', 'language')},
        ),
    ]
