# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 2.2.24 on 2021-11-05 16:52

from django.db import migrations, models

import django_extensions.db.fields.json


class Migration(migrations.Migration):
    dependencies = [
        ("contentful", "0002_rename_contentfulentry_language_to_locale"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentfulentry",
            name="category",
            field=models.CharField(blank=True, default="", help_text="Some pages may have a category", max_length=255),
        ),
        migrations.AddField(
            model_name="contentfulentry",
            name="classification",
            field=models.CharField(
                blank=True,
                default="",
                help_text=(
                    "Some pages may have custom fields on them, distinct "
                    "from their content type - eg: pagePageResourceCenter has a 'Product' field"
                ),
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="contentfulentry",
            name="tags",
            field=django_extensions.db.fields.json.JSONField(blank=True, default=dict, help_text="Some pages may have tags"),
        ),
    ]
