# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 3.2.16 on 2022-11-11 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contentful", "0004_update_unique_constraint_on_contentfulentry"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentfulentry",
            name="localisation_complete",
            field=models.BooleanField(default=False),
        ),
    ]
