# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 3.2.16 on 2022-11-28 10:40

from django.db import migrations


def make_en_us_localisation_complete(apps, schema_editor):
    ContentfulEntry = apps.get_model("contentful", "ContentfulEntry")
    ContentfulEntry.objects.filter(locale="en-US").update(localisation_complete=True)


class Migration(migrations.Migration):
    dependencies = [
        ("contentful", "0005_contentfulentry_localisation_complete"),
    ]

    operations = [
        migrations.RunPython(
            make_en_us_localisation_complete,
            migrations.RunPython.noop,
        ),
    ]
