# Generated by Django 2.2.8 on 2020-01-22 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('releasenotes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productrelease',
            options={'ordering': ['-release_date']},
        ),
    ]
