# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 4.2.18 on 2025-01-27 15:19

from django.db import migrations, models

import bedrock.cms.models.utility


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0002_bedrockimage_bedrockrendition"),
    ]

    operations = [
        migrations.CreateModel(
            name="SimpleKVStore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=64, unique=True)),
                (
                    "value",
                    models.JSONField(encoder=bedrock.cms.models.utility.SetAwareEncoder),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
