# Generated by Django 5.2.7 on 2025-11-11 17:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0003_bedrockimage_description"),
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.CreateModel(
            name="BedrockLocale",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("wagtailcore.locale",),
        ),
    ]
