from .util import gone


redirectpatterns = (
    gone('^catalog/end-user/release$'),
    gone('^help-wanted\.html$'),
    gone('^projects/ui/accessibility/access-radar\.html$'),
    gone('^projects/ui/accessibility/header\.html$'),
    gone('^projects/ui/accessibility/unix/to-do\.html$'),
    gone('^projects/user-docs/$'),
    gone('^projects/user-docs/local/browserhelp/browserbanner\.html$'),
    gone('^projects/user-docs/local/browserhelp/browsercont\.html$'),
    gone('^projects/user-docs/local/browserhelp/browsertoc\.html$'),
    gone('^projects/user-docs/local/browserhelp/browsertop\.html$'),
    gone('^projects/user-docs/local/$'),
    gone('^projects/user-docs/local/mailhelp/mailbanner\.html$'),
    gone('^projects/user-docs/local/mailhelp/mailcont\.html$'),
    gone('^projects/user-docs/local/mailhelp/mailtoc\.html$'),
    gone('^projects/user-docs/local/mailhelp/mailtop\.html$'),
    gone('^projects/user-docs/local/troubleshoot/troublebanner\.html$'),
    gone('^projects/user-docs/local/troubleshoot/troublecont\.html$'),
    gone('^projects/user-docs/local/troubleshoot/troubletoc\.html$'),
    gone('^projects/user-docs/local/troubleshoot/troubletop\.html$'),
    gone('^projects/user-docs/served/custhelp/custbanner\.html$'),
    gone('^projects/user-docs/served/custhelp/custcont\.html$'),
    gone('^projects/user-docs/served/custhelp/custtoc\.html$'),
    gone('^projects/user-docs/served/custhelp/custtop\.html$'),
    gone('^projects/user-docs/served/$'),
    gone('^projects/user-docs/served/shophelp/shopbanner\.html$'),
    gone('^projects/user-docs/served/shophelp/shopcont\.html$'),
    gone('^projects/user-docs/served/shophelp/shoptoc\.html$'),
    gone('^projects/user-docs/served/shophelp/shoptop\.html$'),
    gone('^projects/user-docs/served/updatehelp/updatebanner\.html$'),
    gone('^projects/user-docs/served/updatehelp/updatecont\.html$'),
    gone('^projects/user-docs/served/updatehelp/updatetoc\.html$'),
    gone('^projects/user-docs/served/updatehelp/updatetop\.html$'),
    gone('^projects/user-docs/served/whatsnew/newbanner\.html$'),
    gone('^projects/user-docs/served/whatsnew/newcont\.html$'),
    gone('^projects/user-docs/served/whatsnew/newtoc\.html$'),
    gone('^projects/user-docs/served/whatsnew/newtop\.html$'),
    gone('^xpfe/xptoolkit/xbl\.html$'),
)
