/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

// AUTOGENERATED BY glean_parser v14.5.2. DO NOT EDIT. DO NOT COMMIT.

import EventMetricType from "@mozilla/glean/private/metrics/event";

/**
 * An event containing metrics related to a page level
 * user interaction state that we want to measure.
 * Examples: form completion, scroll events.
 *
 * Generated from `page.interaction`.
 */
export const interaction = new EventMetricType({
    category: "page",
    name: "interaction",
    sendInPings: ["events"],
    lifetime: "ping",
    disabled: false,
}, ["label", "type"]);

/**
 * An event containing metrics related to a page level
 * non-user initiated state that we want to measure.
 * Examples: banner impressions, conditional messaging.
 *
 * Generated from `page.non_interaction`.
 */
export const nonInteraction = new EventMetricType({
    category: "page",
    name: "non_interaction",
    sendInPings: ["events"],
    lifetime: "ping",
    disabled: false,
}, ["label", "type"]);
