# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# See https://github.com/mozilla-l10n/moz-fluent-linter/blob/main/src/fluent_linter/config.yml
# for details

---
ID01:
  enabled: true
  exclusions:
    messages: []
    files: []
ID02:
  enabled: true
  min_length: 6
  exclusions:
    messages: []
    files: []
CO01:
  enabled: true
  brands:
    - Firefox
    - Mozilla
    - Pocket
  exclusions:
    files: []
    messages:
      # firefox/browsers.ftl
      - firefox-browsers-already-have-an-account-sign
      # firefox/browsers/compare/chrome.ftl
      - compare-chrome-weve-also-recently-restated
      # firefox/features/translate.ftl
      - features-translate-for-everyone
      # firefox/privacy/passwords.ftl
      - privacy-passwords-firefox-will
      # firefox/privacy/passwords.ftl
      - privacy-passwords-in-todays-internet
      # mozorg/mission.ftl
      - mission-at-mozilla-were-a-global-community
      # mozorg/mission.ftl
      - mission-read-the-mozilla-manifesto-to-learn
      # mozorg/mission.ftl
      - mission-our-structure-organization-and-the
      # mozorg/newsletters.ftl
      - newsletters-former-university-program
