# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

from django.conf.urls import patterns, url
from util import page
import views

urlpatterns = patterns('',
    url('^$', views.HomeTestView.as_view(), name='mozorg.home'),
    page('about/manifesto', 'mozorg/about/manifesto.html'),
    page('about/manifesto/details', 'mozorg/about/manifesto-details.html'),
    page('about', 'mozorg/about.html'),
    page('book', 'mozorg/book.html'),
    url('^credits/$', views.credits_view, name='mozorg.credits'),
    page('credits/faq', 'mozorg/credits-faq.html'),
    url('^about/partnerships/$', views.partnerships, name='mozorg.partnerships'),
    page('about/partnerships/distribution', 'mozorg/partnerships-distribution.html'),
    page('about/history', 'mozorg/about/history.html'),
    page('about/history/details', 'mozorg/about/history-details.html'),
    page('products', 'mozorg/products.html'),
    page('about/mozilla-based', 'mozorg/projects/mozilla-based.html'),
    page('projects/calendar', 'mozorg/projects/calendar.html'),
    url('^projects/calendar/holidays/$', views.holiday_calendars, name='mozorg.projects.holiday_calendars'),
    page('button', 'mozorg/button.html'),
    page('mission', 'mozorg/mission.html'),
    page('ITU', 'mozorg/itu.html'),
    page('about/powered-by', 'mozorg/powered-by.html'),
    url('^about/forums/$', views.forums_view, name='mozorg.about.forums.forums'),
    page('about/forums/etiquette', 'mozorg/about/forums/etiquette.html'),
    page('about/forums/cancellation', 'mozorg/about/forums/cancellation.html'),
    page('about/governance', 'mozorg/about/governance/governance.html'),
    page('about/governance/roles', 'mozorg/about/governance/roles.html'),
    page('about/governance/policies', 'mozorg/about/governance/policies/policies.html'),
    page('about/governance/policies/security-group/bugs', 'mozorg/about/governance/policies/security/bugs.html'),
    page('about/governance/policies/security-group/tld-idn', 'mozorg/about/governance/policies/security/tld-idn.html'),
    page('about/governance/policies/security-group/membership', 'mozorg/about/governance/policies/security/membership.html'),
    page('about/governance/policies/security-group/certs', 'mozorg/about/governance/policies/security/certs/index.html'),
    page('about/governance/policies/security-group/certs/included', 'mozorg/about/governance/policies/security/certs/included.html'),
    page('about/governance/policies/security-group/certs/pending', 'mozorg/about/governance/policies/security/certs/pending.html'),
    page('about/governance/policies/security-group/certs/policy', 'mozorg/about/governance/policies/security/certs/policy.html'),
    page('about/governance/policies/security-group/certs/policy/enforcement', 'mozorg/about/governance/policies/security/certs/enforcement.html'),
    page('about/governance/policies/security-group/certs/policy/maintenance', 'mozorg/about/governance/policies/security/certs/maintenance.html'),
    page('about/governance/policies/security-group/certs/policy/inclusion', 'mozorg/about/governance/policies/security/certs/inclusion.html'),
    page('about/governance/policies/security/plugin-whitelist-policy', 'mozorg/about/governance/policies/security/plugin-whitelist-policy.html'),
    page('about/governance/organizations', 'mozorg/about/governance/organizations.html'),
    page('about/governance/policies/participation', 'mozorg/about/governance/policies/participation.html'),
    page('about/legal', 'mozorg/about/legal.html'),

    page('contact/spaces', 'mozorg/contact/spaces/spaces-landing.html'),
    page('contact/spaces/mountain-view', 'mozorg/contact/spaces/mountain-view.html'),
    page('contact/spaces/auckland', 'mozorg/contact/spaces/auckland.html'),
    page('contact/spaces/beijing', 'mozorg/contact/spaces/beijing.html'),
    page('contact/spaces/berlin', 'mozorg/contact/spaces/berlin.html'),
    page('contact/spaces/london', 'mozorg/contact/spaces/london.html'),
    page('contact/spaces/paris', 'mozorg/contact/spaces/paris.html'),
    page('contact/spaces/portland', 'mozorg/contact/spaces/portland.html'),
    page('contact/spaces/san-francisco', 'mozorg/contact/spaces/san-francisco.html'),
    page('contact/spaces/taipei', 'mozorg/contact/spaces/taipei.html'),
    page('contact/spaces/tokyo', 'mozorg/contact/spaces/tokyo.html'),
    page('contact/spaces/toronto', 'mozorg/contact/spaces/toronto.html'),
    page('contact/spaces/vancouver', 'mozorg/contact/spaces/vancouver.html'),

    page('contact/communities', 'mozorg/contact/communities/communities-landing.html'),
    page('contact/communities/north-america', 'mozorg/contact/communities/north-america.html'),
    page('contact/communities/latin-america', 'mozorg/contact/communities/latin-america.html'),
    page('contact/communities/europe', 'mozorg/contact/communities/europe.html'),
    page('contact/communities/asia-south-pacific', 'mozorg/contact/communities/asia-south-pacific.html'),
    page('contact/communities/antarctica', 'mozorg/contact/communities/antarctica.html'),
    page('contact/communities/africa-middle-east', 'mozorg/contact/communities/africa-middle-east.html'),
    page('contact/communities/arabic', 'mozorg/contact/communities/arabic.html'),
    page('contact/communities/hispano', 'mozorg/contact/communities/hispano.html'),
    page('contact/communities/francophone', 'mozorg/contact/communities/francophone.html'),

    page('contact/communities/canada', 'mozorg/contact/communities/canada.html'),
    page('contact/communities/united-states', 'mozorg/contact/communities/united-states.html'),
    page('contact/communities/argentina', 'mozorg/contact/communities/argentina.html'),
    page('contact/communities/bolivia', 'mozorg/contact/communities/bolivia.html'),
    page('contact/communities/brazil', 'mozorg/contact/communities/brazil.html'),
    page('contact/communities/chile', 'mozorg/contact/communities/chile.html'),
    page('contact/communities/colombia', 'mozorg/contact/communities/colombia.html'),
    page('contact/communities/costa-rica', 'mozorg/contact/communities/costa-rica.html'),
    page('contact/communities/cuba', 'mozorg/contact/communities/cuba.html'),
    page('contact/communities/ecuador', 'mozorg/contact/communities/ecuador.html'),
    page('contact/communities/mexico', 'mozorg/contact/communities/mexico.html'),
    page('contact/communities/nicaragua', 'mozorg/contact/communities/nicaragua.html'),
    page('contact/communities/paraguay', 'mozorg/contact/communities/paraguay.html'),
    page('contact/communities/peru', 'mozorg/contact/communities/peru.html'),
    page('contact/communities/uruguay', 'mozorg/contact/communities/uruguay.html'),
    page('contact/communities/venezuela', 'mozorg/contact/communities/venezuela.html'),

    page('contact/communities/albania', 'mozorg/contact/communities/albania.html'),
    page('contact/communities/armenia', 'mozorg/contact/communities/armenia.html'),
    page('contact/communities/austria', 'mozorg/contact/communities/austria.html'),
    page('contact/communities/basque', 'mozorg/contact/communities/basque.html'),
    page('contact/communities/belgium', 'mozorg/contact/communities/belgium.html'),
    page('contact/communities/bosnia-and-herzegovina', 'mozorg/contact/communities/bosnia-and-herzegovina.html'),
    page('contact/communities/bulgaria', 'mozorg/contact/communities/bulgaria.html'),
    page('contact/communities/catalan', 'mozorg/contact/communities/catalan.html'),
    page('contact/communities/croatia', 'mozorg/contact/communities/croatia.html'),
    page('contact/communities/czech-republic', 'mozorg/contact/communities/czech-republic.html'),
    page('contact/communities/denmark', 'mozorg/contact/communities/denmark.html'),
    page('contact/communities/finland', 'mozorg/contact/communities/finland.html'),
    page('contact/communities/france', 'mozorg/contact/communities/france.html'),
    page('contact/communities/germany', 'mozorg/contact/communities/germany.html'),
    page('contact/communities/greece', 'mozorg/contact/communities/greece.html'),
    page('contact/communities/hungary', 'mozorg/contact/communities/hungary.html'),
    page('contact/communities/ireland', 'mozorg/contact/communities/ireland.html'),
    page('contact/communities/italy', 'mozorg/contact/communities/italy.html'),
    page('contact/communities/kosovo', 'mozorg/contact/communities/kosovo.html'),
    page('contact/communities/lithuania', 'mozorg/contact/communities/lithuania.html'),
    page('contact/communities/norway', 'mozorg/contact/communities/norway.html'),
    page('contact/communities/poland', 'mozorg/contact/communities/poland.html'),
    page('contact/communities/portugal', 'mozorg/contact/communities/portugal.html'),
    page('contact/communities/macedonia', 'mozorg/contact/communities/macedonia.html'),
    page('contact/communities/romania', 'mozorg/contact/communities/romania.html'),
    page('contact/communities/russia', 'mozorg/contact/communities/russia.html'),
    page('contact/communities/serbia', 'mozorg/contact/communities/serbia.html'),
    page('contact/communities/slovakia', 'mozorg/contact/communities/slovakia.html'),
    page('contact/communities/slovenia', 'mozorg/contact/communities/slovenia.html'),
    page('contact/communities/spain', 'mozorg/contact/communities/spain.html'),
    page('contact/communities/switzerland', 'mozorg/contact/communities/switzerland.html'),
    page('contact/communities/the-netherlands', 'mozorg/contact/communities/the-netherlands.html'),
    page('contact/communities/turkey', 'mozorg/contact/communities/turkey.html'),
    page('contact/communities/ukraine', 'mozorg/contact/communities/ukraine.html'),
    page('contact/communities/united-kingdom', 'mozorg/contact/communities/united-kingdom.html'),

    page('contact/communities/australia', 'mozorg/contact/communities/australia.html'),
    page('contact/communities/bangladesh', 'mozorg/contact/communities/bangladesh.html'),
    page('contact/communities/cambodia', 'mozorg/contact/communities/cambodia.html'),
    page('contact/communities/china', 'mozorg/contact/communities/china.html'),
    page('contact/communities/hong-kong', 'mozorg/contact/communities/hong-kong.html'),
    page('contact/communities/india', 'mozorg/contact/communities/india.html'),
    page('contact/communities/indonesia', 'mozorg/contact/communities/indonesia.html'),
    page('contact/communities/japan', 'mozorg/contact/communities/japan.html'),
    page('contact/communities/kerala', 'mozorg/contact/communities/kerala.html'),
    page('contact/communities/malaysia', 'mozorg/contact/communities/malaysia.html'),
    page('contact/communities/myanmar', 'mozorg/contact/communities/myanmar.html'),
    page('contact/communities/nepal', 'mozorg/contact/communities/nepal.html'),
    page('contact/communities/pakistan', 'mozorg/contact/communities/pakistan.html'),
    page('contact/communities/philippines', 'mozorg/contact/communities/philippines.html'),
    page('contact/communities/singapore', 'mozorg/contact/communities/singapore.html'),
    page('contact/communities/south-korea', 'mozorg/contact/communities/south-korea.html'),
    page('contact/communities/sri-lanka', 'mozorg/contact/communities/sri-lanka.html'),
    page('contact/communities/taiwan', 'mozorg/contact/communities/taiwan.html'),
    page('contact/communities/thailand', 'mozorg/contact/communities/thailand.html'),
    page('contact/communities/vietnam', 'mozorg/contact/communities/vietnam.html'),

    page('contact/communities/algeria', 'mozorg/contact/communities/algeria.html'),
    page('contact/communities/ivory-coast', 'mozorg/contact/communities/ivory-coast.html'),
    page('contact/communities/egypt', 'mozorg/contact/communities/egypt.html'),
    page('contact/communities/ghana', 'mozorg/contact/communities/ghana.html'),
    page('contact/communities/israel', 'mozorg/contact/communities/israel.html'),
    page('contact/communities/jordan', 'mozorg/contact/communities/jordan.html'),
    page('contact/communities/kenya', 'mozorg/contact/communities/kenya.html'),
    page('contact/communities/mauritius', 'mozorg/contact/communities/mauritius.html'),
    page('contact/communities/palestine', 'mozorg/contact/communities/palestine.html'),
    page('contact/communities/senegal', 'mozorg/contact/communities/senegal.html'),
    page('contact/communities/tunisia', 'mozorg/contact/communities/tunisia.html'),
    page('contact/communities/uganda', 'mozorg/contact/communities/uganda.html'),
    page('contact/communities/zimbabwe', 'mozorg/contact/communities/zimbabwe.html'),

    url('^contribute/$', views.contribute, name='mozorg.contribute',
        kwargs={'template': 'mozorg/contribute.html',
                'return_to_form': False}),
    url('^contribute/event/$', views.contribute,
        kwargs={'template': 'mozorg/contribute.html',
                'return_to_form': True},
        name='mozorg.contribute_event'),
    url('^contribute/page/$', views.contribute,
        kwargs={'template': 'mozorg/contribute-page.html',
                'return_to_form': False},
        name='mozorg.contribute_page'),
    url('^contribute/embed/$', views.contribute_embed,
        name='mozorg.contribute_embed',
        kwargs={'template': 'mozorg/contribute-embed.html',
                'return_to_form': False}),
    url('^contribute/studentambassadors/$',
        views.contribute_studentambassadors_landing,
        name='mozorg.contribute.studentambassadors.landing'),
    url('^contribute/studentambassadors/join/$',
        views.contribute_studentambassadors_join,
        name='mozorg.contribute.studentambassadors.join'),
    page('contribute/studentambassadors/thanks',
         'mozorg/contribute/studentambassadors/thanks.html'),
    url(r'^plugincheck/$',
        views.plugincheck,
        name='mozorg.plugincheck'),
    url(r'^robots.txt$', views.Robots.as_view(), name='robots.txt'),
)
