# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.17 on 2026-09-30 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_auto_20200122_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='data',
            field=models.JSONField(default=dict),
        ),
    ]
