# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

### Privacy URL: https://dev.tekcopteg.com/privacy/

pocket-privacy-title = Privacy
pocket-privacy-policy = Privacy Policy
pocket-privacy-posted = Posted October 11, 2021
pocket-privacy-this-notice = This notice describes the Privacy Policy that applies to all information collected or submitted when you install or use the { -brand-name-pocket } application or any of the other proprietary software applications or services we provide, and when you visit our website (all of which are referred to collectively herein as the “{ -brand-name-pocket-technologies }”). The { -brand-name-pocket-technologies } are owned and licensed by { -brand-name-mozilla-corporation } (referred to herein as “we”, “us”, “our”, “{ -brand-name-mozilla }”), and are operated by { -brand-name-mozilla }’s business unit known as “{ -brand-name-pocket }”, which has developed applications and services for use in connection with a variety of devices and platforms, including without limitation, { -brand-name-windows }, { -brand-name-mac-short }, { -brand-name-iphone }, { -brand-name-ipad }, { -brand-name-kindle-fire }, { -brand-name-android }, { -brand-name-blackberry }, { -brand-name-windows } phone, { -brand-name-chrome }, { -brand-name-safari }, { -brand-name-firefox } and other mobile devices and computers.
pocket-privacy-we-understand = We understand your concerns about privacy. We want you to understand what types of information we collect and what may happen to that information if you install the { -brand-name-pocket } application, visit the { -brand-name-pocket } Website or use any of the { -brand-name-pocket-technologies }.
# the word jump here is being used as verb - alt: "you can naviagate to.."
pocket-privacy-our-privacy-policy = Our Privacy Policy includes the following provisions, and you can jump to each by selecting the links below:
pocket-privacy-user-accounts = User Accounts and Collection of Information
pocket-privacy-collection-of-information = Collection of Information as Part of Using { -brand-name-pocket } Service
pocket-privacy-use-of-cookies = Use of Cookies and Analytics
pocket-privacy-use-of-information = Use of Information
pocket-privacy-sharing = Sharing of Information
pocket-privacy-keeping = Keeping of Information
pocket-privacy-transfer = Transfer of Information
pocket-privacy-security = Security
pocket-privacy-phishing = Phishing
pocket-privacy-managing-my-privacy = Managing My Privacy and Email Settings
pocket-privacy-amendments = Amendments to Policy
pocket-privacy-contact = Contact

pocket-privacy-you-are-not-required = You are not required to create a user account or provide any personal information in order to visit the { -brand-name-pocket } website. You are required to create a user account, however, to use our application. During registration, you are required to provide a name, password and valid email address.
pocket-privacy-if-you-choose = If you choose to share any articles, videos, or other content with another person, we will ask you to provide a valid email address for that person. We may also ask you to provide your username and password for third party websites in order to access the articles and information published on such sites. We also collect information if you contact us for support or help, submit an application or otherwise communicate with us. The information which you supply to us enables us to customize and enhance the services we provide to you. In addition, it helps us communicate with you about our news, events, promotions and new products.
pocket-privacy-if-you-choose-to-subscribe = If you choose to subscribe to our paid subscription service, our third party payment processors will collect and handle your credit card and related payment information. Such third party processors’ use of your personal information is governed by their respective privacy policies.
pocket-privacy-in-addition = In addition to the information that you provide to us when you register for a user account, we collect information about the URLs, titles and content of the web pages and other information you save to { -brand-name-pocket }. The types of information we collect includes your browser type, device type, time zone, language, and other information related to the manner in which you access the { -brand-name-pocket-technologies }. If you are on a mobile device, we collect the advertising identifiers provided by { -brand-name-apple } on { -brand-name-ios } and by { -brand-name-google } on { -brand-name-android }. You can change this identifier in your device settings. We also collect information about your use of the { -brand-name-pocket-technologies } so that we can provide our services. For example, as a part of providing { -brand-name-pocket }’s syncing features, we sync information about the items that you save and view within { -brand-name-pocket } so that your list, tags, scroll position, and other account and usage information may be synced across all of your devices.
pocket-privacy-types = Types and Purposes
pocket-privacy-we-use-cookies = We use cookies and analytics tools for the following purposes:
pocket-privacy-necessary = Necessary: These cookies are necessary for our website to function and to support our business. They cannot be switched off. For example, we use them to manage your login state, and our ad partners use them to display ads and measure impressions and clicks. You can set your browser to block or alert you about these cookies, but this may cause parts of the site to not work properly. These cookies do not store any personally identifiable information and unless Personalized Advertising Cookies are enabled, ads are non-personalized.
pocket-privacy-analytics = Analytics: We place these cookies on your device to help us understand how users engage with our website and product, and to remember your account preferences and language settings. For example, we use { -brand-name-google } Analytics and other tools to understand which { -brand-name-pocket } webpages are popular. We also use pixels in our emails in order to collect usage information.
pocket-privacy-personalized = Personalized Advertising: Some { -brand-name-pocket } web pages have ads. If you choose, { -brand-name-pocket } ad partners will place advertising cookies on your device to personalize the ads you see here and on other websites. If you play a { -brand-name-youtube } video on { -brand-name-pocket }, { -brand-name-youtube } may place cookies on your device which can be used for personalization.
pocket-privacy-your-choices = Your choices
# Variables:
#   $cookie_button_id: (String) ot-sdk-btn
#   $cookie_button_class: (String) ot-sdk-show-settings
#   $cookie_faq_link: (String) https://help.getpocket.com/article/1163-pocket-website-cookies-faq
pocket-privacy-cookie-preference = Cookie Preference tool: By default, { -brand-name-pocket } sets necessary and analytics cookies, and disables personalized advertising cookies. You can manage these cookies from this <button id="{ $cookie_button_id }" class="{ $cookie_button_class }">Cookie Prefrences</button> tool. <a { $cookie_faq_link_attr } href="{ $cookie_faq_link }">Learn more</a>.
pocket-privacy-your-browser = Your browser: Your browser preferences menu can help you manage cookies and prevent cross-site tracking.
# Variables
#   $ga_opt_out_link: (String) https://tools.google.com/dlpage/gaoptout
pocket-privacy-google-analytics-opt = { -brand-name-google-analytics } opt-out: Install the <a href="{ $ga_opt_out_link }">{ -brand-name-google-analytics }  Opt-out Browser Add-on</a>, which prohibits data transmission to { -brand-name-google-analytics }.
# Variables
#  $opt_out_link_1: (String) https://optout.networkadvertising.org/?c=1
#  $opt_out_link_2: (String) https://optout.aboutads.info/?c=2&lang=EN
#  $opt_out_link_3: (String) https://www.youronlinechoices.com/uk/your-ad-choices
pocket-privacy-external-opt-out = External opt-out tools: Some third-party organizations provide ways of opting out of personalized advertising delivered by participating companies. For information about how to opt-out, you can visit these organizations’ websites: <a href="{ $opt_out_link_1 }">Network Advertising Initiative’s opt-out tools</a>, the <a href="{ $opt_out_link_2 }">Digital Advertising Initiative’s Browser Check tool</a>, and the <a href="{ $opt_out_link_3 }">European Interactive Digital Advertising Alliance Your Ad Choices</a>.
pocket-privacy-your-right-to-opt = Your Right to Opt-Out of the Sale of Personal Information: { -brand-name-pocket } does not share or sell your personal information. If you enable personalized advertising on { -brand-name-pocket }, we allow advertisers to personalize your ads on { -brand-name-pocket } and this may be considered a sale of your information under California’s privacy law. You can opt-out by navigating to your Cookie Preference tool → Personalized Advertising Cookies and toggling to “disabled”.
pocket-privacy-in-addition-to-the-methods = In addition to the methods described above, we may also collect information using cookies or other technologies when you access our website or use { -brand-name-pocket }. You may decline our cookies if your browser permits, although in that case you may not be able to use certain features, you may be required to enter your password more frequently during a session, and you may be unable to install or use certain { -brand-name-pocket }. Cookies and other technologies make our { -brand-name-pocket } easier to use and help us customize and personalize the services we provide based on your interests and activities.
pocket-privacy-we-may-also = We may also use “pixel tags”, “web beacons”, “clear GIFs” or similar means (individually or collectively “Pixel Tags”) in connection with emails that we send to our users in order to collect usage data. We use Pixel Tags, other technologies and the information we collect to count users who have visited certain pages on our Website, to deliver branded services and to help determine the effectiveness of promotional or advertising campaigns.
pocket-privacy-we-use-your-personal = We use your personal information to respond to your requests and perform our contract with you. We may do this, for example, by using your contact information to respond to your inquiries, to provide customer support and to supply any products or services you have requested. In addition, if you choose to use the { -brand-name-pocket-technologies } to share content with another person, we will use the recipient’s email address or user account information to provide that service, but we will not use that email address for any other purpose.
pocket-privacy-we-also-have = We also have a legitimate business interest to operate and improve our services such as saving articles, videos, or other content to { -brand-name-pocket } and making such content and recommendations available to you at a later time on any device that you use to access the { -brand-name-pocket-technologies }. We also use non-identifying, aggregated information to analyze the manner in which the { -brand-name-pocket-technologies } are used, which also allows us to improve our services. The aggregated information we use includes the manner in which articles, videos, or content has been accessed, saved and shared. We may use aggregated information to offer a list of top sites or content, to make recommendations to our users, to report on usage and trends, to improve the products and services that we offer, or to develop new products and services.
pocket-privacy-except-as-set = Except as set forth below, we do not share any personally identifiable information unless you expressly agree that we may do so.
pocket-privacy-public-content = Public content
pocket-privacy-if-you-choose-to-make = If you choose to make the content you save publicly available, we may share that information with others in accordance with the options you select. In addition, if you choose to use the { -brand-name-pocket-technologies } to share articles, videos, or other content with another person, we will send an email on your behalf to that person with a link to the content that you have chosen to share.
pocket-privacy-aggregate-data = Aggregate data
pocket-privacy-we-also-share = We also share aggregated, non-personal data and related usage information, which does not contain any personal information which can identify you or any other individual user, with third parties, including content providers, website operators, advertisers and publishers. For example, we may share with a content provider a list of the most saved articles to { -brand-name-pocket } based on an analysis of aggregated, anonymous user data, but we would not share with such content provider any personal information regarding such users.
pocket-privacy-links-to-other = Links to other sites and apps
pocket-privacy-if-you-choose-to-you-may = If you choose to, you may connect your { -brand-name-pocket } account to third-party applications to enable additional features like saving from your favorite apps or other unique features third-party developers have created. We have set up controls in the { -brand-name-pocket } application so that you can control the information that is shared with third-party providers of products and services. For example, you may be informed that another app that you use wants to connect to your { -brand-name-pocket } account. In some cases, such apps will request access to certain data in your { -brand-name-pocket } account, such as your { -brand-name-pocket } list or your preferred topics, sites and authors (which we have developed based on the content you have saved to { -brand-name-pocket }), so that they can customize their services. Before such access is provided, however, you will be asked to authorize the sharing of any such information. Although the { -brand-name-pocket-technologies } may be used in conjunction with third-party products and services, we are not affiliated with, and have no control over, such third parties. Except as otherwise expressly included in this Privacy Policy, this document only addresses the use and disclosure of information we collect from you and we encourage you to check the privacy policy of each third-party provider of products or services that you choose to connect your { -brand-name-pocket } account to.
pocket-privacy-working = Working with third parties
pocket-privacy-we-may-work = We may work with trusted third parties to facilitate one or more aspects of the products, services, or features that we provide to you, and we may provide some of your personal information directly to these third parties. For example, as discussed above, we may use a third party payment processor to process payments for our paid subscription service. We may also share limited aggregated data with our advertising partners (read more in the “Aggregate data” section above). These parties are subject to confidentiality agreements with us and other legal restrictions that prohibit their use of the information we provide to them for any other purpose other than those discussed above, unless you have explicitly agreed or given your prior permission to them for additional uses. If you use the “Listen” feature, we may share the content of the article with a third party service in order to read the article aloud.
pocket-privacy-sharing-as-required = Sharing as required by law or asset sale
pocket-privacy-in-the-event = In the event that we or certain of our assets are acquired, user information may be included among the transferred assets.
pocket-privacy-although = Although we strive to protect the personal information of our users, we will release personal information if required by law or in the good-faith belief that such action is necessary. We follow the law whenever we receive requests about you from a government or related to a lawsuit. We will notify you when we are asked to hand over your personally identifiable information in this way unless we are legally prohibited from doing so. When we receive requests like this, we will only release your personally identifiable information if we have a good faith belief that disclosure is necessary or appropriate under applicable law. Nothing in this policy is intended to limit any legal defenses or objections that you may have to a third party’s request to disclose your information.

pocket-privacy-we-will = We will keep your information only for as long as we need it to provide you services, manage our business or as required by law or contract.
pocket-privacy-were-a-global = We’re a global organization and our computers are in several different places around the world. We also use service providers whose computers may also be in various countries. This means that your information might end up on one of those computers in another country, and that country may have a different level of data protection regulation than yours. By giving us information, you consent to this kind of transfer of your information. No matter what country your information is in, we comply with applicable law and will also abide by the commitments we make in this privacy policy.
pocket-privacy-we-have-agreements = We have agreements with third parties and have adopted other security measures in place to protect against the loss, misuse and/or unauthorized alteration of the information under our control or under the control of our service providers. Your personally identifiable information is protected by utilizing both online and offline security methods, including firewalls, passwords and restricted physical access to the places where your information is stored. Although we use industry standard practices to protect your privacy, we do not promise, and you should not expect, that your personal information or private communications will always remain free from security issues. In the event of a security breach involving your personal information, we will make any legally required disclosures to you in the most expedient time possible and without unreasonable delay, consistent with the legitimate interests of law enforcement, or any measures necessary to determine the scope of the breach and restore the reasonable integrity of the data system.
pocket-privacy-identity-theft = Identity theft and the practice currently known as “phishing” are of great concern to { -brand-name-pocket }. Safeguarding information to help protect you from identity theft is a top priority. We do not and will not, at any time, request your username, password, credit card information or national identification number in an unsolicited e-mail or telephone communication. For more information about phishing, visit the Federal Trade Commission’s website.
# Variables
#   $pocket_options_url: (String) https://getpocket.com/options
pocket-privacy-you-can-access = You can access, correct, or delete your personal information and export your data from your { -brand-name-pocket } Profile. You can also view and control which third party services, if any, you want to connect to your { -brand-name-pocket } account. These settings are at: <a href="{ $pocket_options_url }">{ $pocket_options_url }</a>
pocket-privacy-as-part = As part of our default settings to share saved and recommended content, we send emails to our users. You may opt-out of receiving these, and updates on our service and your use, by using the unsubscribe feature on any of our email correspondence or from your account settings. We will try to communicate with you only according to your instructions, although it may take some time to process your request.
# Variables:
#   $pocket_home_page: (String) getpocket.com
pocket-privacy-please-note = Please note this Privacy Policy will change from time to time. We may amend this Privacy Policy at any time by posting the amended terms on our Website that you can access at { $pocket_home_page } or through the options or help menu of the { -brand-name-pocket } application. All amended terms shall automatically be effective thirty (30) days after they are initially posted on the Website. If we make any material changes to our Privacy Policy that affect user information already stored in our database, we will post a prominent notice on our Website notifying users that our Privacy Policy has changed. Our use of your information shall be governed by the terms and conditions of our Privacy Policy in effect when you first use our application or thirty (30) after the terms are changed, as explained above.
# Variables:
#   $pocket_privacy_email_href: (String) mailto:privacy@getpocket.com
#   $pocket_privacy_email: (String) privacy@getpocket.com
pocket-privacy-if-you-have = If you have questions about any of the provisions described above, please contact us at <a href="{ $pocket_privacy_email_href }">{ $pocket_privacy_email }</a> or at the street address listed above.
# Variables:
#   $pocket_privacy_email_href: (String) mailto:privacy@getpocket.com
#   $pocket_privacy_email: (String) privacy@getpocket.com
#   $pocket_help_contact_link: (String) https://help.getpocket.com/contact
pocket-privacy-if-you-have-questions = If you have questions or concerns regarding this Privacy Policy, you should contact us at <a href="{ $pocket_privacy_email_href }">{$pocket__privacy_email}</a> or <a href="{$pocket_help_contact_link}">{ $pocket_help_contact_link }</a>. Alternatively, you may contact us at:
pocket-privacy-european = Europeans who believe a privacy complaint is unresolved have the right to lodge a complaint with the supervisory authority of their Member State.
