# For locales with dedicated templates that don't go through
# the Fluent localization process by either vendor or pontoon,
# list the ftl file and the locales handled by the templates
# in [[paths]] sections here.

basepath = ".."

## Example:

# [[paths]]
#     reference = "en/firefox/home.ftl"
#     l10n = "{locale}/firefox/home.ftl"
#     locales = [
#         "de",
#         "fr",
#     ]

[[paths]]
    reference = "en/products/vpn/platforms/*.ftl"
    l10n = "{locale}/products/vpn/platforms/*.ftl"
    locales = [
    "ach",
    "af",
    "am",
    "an",
    "ar",
    "ast",
    "az",
    "azz",
    "be",
    "bg",
    "bn",
    "br",
    "bs",
    "ca",
    "cak",
    "crh",
    "cs",
    "cy",
    "da",
    "de",
    "dsb",
    "el",
    "en-CA",
    "en-GB",
    "eo",
    "es-AR",
    "es-CL",
    "es-ES",
    "es-MX",
    "et",
    "eu",
    "fa",
    "ff",
    "fi",
    "fr",
    "fy-NL",
    "ga-IE",
    "gd",
    "gl",
    "gn",
    "gu-IN",
    "he",
    "hi-IN",
    "hr",
    "hsb",
    "hto",
    "hu",
    "hy-AM",
    "ia",
    "id",
    "is",
    "it",
    "ja",
    "ka",
    "kab",
    "kk",
    "km",
    "kn",
    "ko",
    "lij",
    "lo",
    "lt",
    "ltg",
    "lv",
    "mk",
    "ml",
    "mr",
    "ms",
    "my",
    "nb-NO",
    "ne-NP",
    "nl",
    "nn-NO",
    "nv",
    "oc",
    "pa-IN",
    "pai",
    "pbb",
    "pl",
    "pt-BR",
    "pt-PT",
    "qvi",
    "rm",
    "ro",
    "ru",
    "si",
    "sk",
    "sl",
    "son",
    "sq",
    "sr",
    "sv-SE",
    "sw",
    "ta",
    "te",
    "th",
    "tl",
    "tr",
    "trs",
    "uk",
    "ur",
    "uz",
    "vi",
    "wo",
    "xh",
    "zam",
    "zh-CN",
    "zh-TW",
    "zu",
    ]
