# Generated by Django 5.2.9 on 2026-01-27

from django.db import migrations


def update_content_types(apps, schema_editor):
    """Update ContentType references from mozorg to advertising."""
    ContentType = apps.get_model("contenttypes", "ContentType")
    Page = apps.get_model("wagtailcore", "Page")

    model_names = [
        "advertisingindexpage",
        "advertisingtwocolumnsubpage",
        "contentsubpage",
    ]

    for model_name_lower in model_names:
        try:
            # Get the old mozorg ContentType
            old_ct = ContentType.objects.get(app_label="mozorg", model=model_name_lower)
            # Get or create the new advertising ContentType
            new_ct, created = ContentType.objects.get_or_create(
                app_label="advertising",
                model=model_name_lower,
            )

            # Update all Page objects that use the old ContentType
            num_updated = Page.objects.filter(content_type=old_ct).update(content_type=new_ct)

            print(f"Updated {num_updated} pages from mozorg.{model_name_lower} to advertising.{model_name_lower}")

            # Delete the old ContentType
            old_ct.delete()
            print(f"Deleted old ContentType: mozorg.{model_name_lower}")

        except ContentType.DoesNotExist:
            print(f"ContentType mozorg.{model_name_lower} not found, skipping")


def reverse_content_types(apps, schema_editor):
    """Reverse the ContentType update (for rollback)."""
    ContentType = apps.get_model("contenttypes", "ContentType")
    Page = apps.get_model("wagtailcore", "Page")

    model_names = [
        "advertisingindexpage",
        "advertisingtwocolumnsubpage",
        "contentsubpage",
    ]

    for model_name_lower in model_names:
        try:
            # Get the advertising ContentType
            new_ct = ContentType.objects.get(app_label="advertising", model=model_name_lower)
            # Recreate the mozorg ContentType
            old_ct, created = ContentType.objects.get_or_create(
                app_label="mozorg",
                model=model_name_lower,
            )

            # Update all Page objects back to mozorg ContentType
            Page.objects.filter(content_type=new_ct).update(content_type=old_ct)

            # Delete the advertising ContentType if no pages use it
            if not Page.objects.filter(content_type=new_ct).exists():
                new_ct.delete()

        except ContentType.DoesNotExist:
            pass


class Migration(migrations.Migration):
    dependencies = [
        ("advertising", "0001_initial"),
        ("mozorg", "0025_remove_advertisingtwocolumnsubpage_page_ptr_and_more"),
        ("contenttypes", "__latest__"),
        ("wagtailcore", "__latest__"),
    ]

    operations = [
        migrations.RunPython(update_content_types, reverse_content_types),
    ]
