from django.conf.urls.defaults import *
from mozorg.hierarchy import node, nodeview

hierarchy = node('Styleguide',
    nodeview('Home', '', 'styleguide/home.html'),
    node('Identity',
        node('Mozilla',
            nodeview('Branding', 'identity/mozilla/branding', 'styleguide/identity/mozilla-branding.html'),
            nodeview('Color', 'identity/mozilla/color', 'styleguide/identity/mozilla-color.html'),
            nodeview('Innovations', 'identity/mozilla/innovations', 'styleguide/identity/mozilla-innovations.html'),
        ),
        node('Firefox Browser',
            nodeview('Branding', 'identity/firefox/branding', 'styleguide/identity/firefox-branding.html'),
            nodeview('Channels', 'identity/firefox/channels', 'styleguide/identity/firefox-channels.html'),
            nodeview('Wordmarks', 'identity/firefox/wordmarks', 'styleguide/identity/firefox-wordmarks.html'),
            nodeview('Color', 'identity/firefox/color', 'styleguide/identity/firefox-color.html'),
        ),
        node('Firefox OS',
            nodeview('Branding', 'identity/firefoxos/branding', 'styleguide/identity/firefoxos-branding.html'),
        ),
        node('Firefox Family',
            nodeview('Overview', 'identity/firefox-family/overview', 'styleguide/identity/firefox-family-overview.html'),
            nodeview('Platform', 'identity/firefox-family/platform', 'styleguide/identity/firefox-family-platform.html'),
        ),
        node('Marketplace',
            nodeview('Branding', 'identity/marketplace/branding', 'styleguide/identity/marketplace-branding.html'),
            nodeview('Color', 'identity/marketplace/color', 'styleguide/identity/marketplace-color.html'),
        ),
        node('Webmaker',
            nodeview('Branding', 'identity/webmaker/branding', 'styleguide/identity/webmaker-branding.html'),
            nodeview('Color', 'identity/webmaker/color', 'styleguide/identity/webmaker-color.html'),
        ),
        node('Thunderbird',
            nodeview('Logo', 'identity/thunderbird/logo', 'styleguide/identity/thunderbird-logo.html'),
            nodeview('Channels', 'identity/thunderbird/channels', 'styleguide/identity/thunderbird-channels.html'),
            nodeview('Wordmarks', 'identity/thunderbird/wordmarks', 'styleguide/identity/thunderbird-wordmarks.html'),
            nodeview('Color', 'identity/thunderbird/color', 'styleguide/identity/thunderbird-color.html'),
        ),
    ),
    node('Websites',
        node('Sandstone',
            nodeview('Overview', 'sandstone', 'styleguide/websites/sandstone-intro.html'),
            nodeview('Buttons', 'sandstone/buttons', 'styleguide/websites/sandstone-buttons.html'),
            nodeview('Colors', 'sandstone/colors', 'styleguide/websites/sandstone-colors.html'),
            nodeview('Forms', 'sandstone/forms', 'styleguide/websites/sandstone-forms.html'),
            nodeview('Grids', 'sandstone/grids', 'styleguide/websites/sandstone-grids.html'),
            nodeview('Tables', 'sandstone/tables', 'styleguide/websites/sandstone-tables.html'),
            nodeview('Tabzilla', 'sandstone/tabzilla', 'styleguide/websites/sandstone-tabzilla.html'),
            nodeview('Typefaces', 'sandstone/typefaces', 'styleguide/websites/sandstone-typefaces.html'),
            nodeview('Examples', 'sandstone/examples', 'styleguide/websites/sandstone-examples.html'),
        ),
        nodeview('Community sites', 'websites/community/overview', 'styleguide/websites/community-overview.html'),
        nodeview('Domain strategy', 'websites/domains/overview', 'styleguide/websites/domains-overview.html'),
    ),
    node('Communications',
        nodeview('Presentations', 'communications/presentations', 'styleguide/communications/presentations.html'),
        nodeview('Video', 'communications/video', 'styleguide/communications/video.html'),
        nodeview('Typefaces', 'communications/typefaces', 'styleguide/communications/typefaces.html'),
        nodeview('Copy tone', 'communications/copy-tone', 'styleguide/communications/copy-tone.html'),
        nodeview('Copy rules', 'communications/copy-rules', 'styleguide/communications/copy-rules.html'),
        nodeview('Translation', 'communications/translation', 'styleguide/communications/translation.html'),
    ),
)

urlpatterns = hierarchy.as_urlpattern()
