# see the following for documentation of these options
# http://bedrock.readthedocs.io/en/latest/pipeline.html#configuration
push_public_registry: true
smoke_tests: true
require_tag: true
regions:
  - usw
  - tokyo
  - frankfurt
  - oregon-b
apps:
  - bedrock-stage
  - bedrock-prod
integration_tests:
  usw:
    - headless
    - download
    - firefox
    - chrome
    - ie
    - ie8
  tokyo:
    - firefox
  frankfurt:
    - firefox
  oregon-b:
    - firefox
