# see the following for documentation of these options
# http://bedrock.readthedocs.io/en/latest/pipeline.html#configuration
push_public_registry: true
require_tag: true
regions:
  - iowa-a
  - frankfurt
apps:
  - bedrock-prod
integration_tests:
  frankfurt:
    - headless
  iowa-a:
    - chrome
    - download
    - firefox
    - headless
    - ie
    - ie9
