# Generated by Django 2.2.13 on 2020-11-05 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SitemapURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=200)),
                ('locale', models.CharField(max_length=5)),
                ('lastmod', models.CharField(blank=True, max_length=40)),
            ],
        ),
    ]
