name: Fluent Linter
on:
  push:
    paths:
      - "l10n/en/**.ftl"
      - ".github/l10n/*"
      - ".github/workflows/fluent_linter.yml"
    branches:
      - main
  pull_request:
    paths:
      - "l10n/en/**.ftl"
      - ".github/l10n/*"
      - ".github/workflows/fluent_linter.yml"
    branches:
      - main
  workflow_dispatch:
jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Python 3
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install Python dependencies
        run: |
          pip install -r .github/l10n/requirements.txt
      - name: Lint mozilla.org files
        run: |
          moz-fluent-lint l10n/en --config .github/l10n/linter_config.yml
      - name: Check TOML files
        run: |
          python .github/l10n/check_toml_configs.py --path .
