name: Fluent Linter
on:
  push:
    paths:
      - "l10n/en/**.ftl"
      - ".github/l10n/*"
      - ".github/workflows/fluent_linter.yml"
    branches:
      - main
  pull_request:
    paths:
      - "l10n/en/**.ftl"
      - ".github/l10n/*"
      - ".github/workflows/fluent_linter.yml"
    branches:
      - main
  workflow_dispatch:
jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      - name: Set up Python 3
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: "3.13"
      - name: Install Python dependencies
        run: |
          pip install -r .github/l10n/requirements.txt
      - name: Lint mozilla.org files
        run: |
          moz-fluent-lint l10n/en --config .github/l10n/linter_config.yml
      - name: Check TOML files
        run: |
          python .github/l10n/check_toml_configs.py --path .
