name: Unit tests
on: [pull_request]
jobs:
  test-js:
    runs-on: ubuntu-latest
    steps:
      - name: "Install framebuffer (xvfb), FF and Chromium"
        run: |
          sudo apt-get update
          sudo apt-get install chromium-browser firefox xvfb
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: "Install JS dependencies"
        run: npm ci
      - name: "Set NO_PROXY to ensure Karma can connect"
        run: export NO_PROXY="localhost, 0.0.0.0/4201, 0.0.0.0/9876"
      - name: "Run JS tests"
        run: xvfb-run npm test
