name: Unit tests
on:
  push:
    branches:
      - 'main'
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-compose-action@v1
        with:
          version: v2.38.1
      - name: "Basically docker compose build app assets …"
        run: |
            make clean test-image            
        timeout-minutes: 10
