name: Test documentation build

on:
  workflow_dispatch: # allow manual runs
  pull_request:
    paths: # only build on relevant changes
      - docs/**
      - requirements/docs.*
      - .github/workflows/pull_request_test_docs.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: 3.13
          cache: pip
      - run: pip install -r requirements/docs.txt
      - run: cd docs && mkdocs build --strict
