name: Unit tests
on:
  push:
    branches:
      - 'main'
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test-js:
    runs-on: ubuntu-latest
    steps:
      - name: "Install framebuffer (xvfb) and Chromium"
        run: |
          sudo apt-get update
          sudo apt-get install chromium-browser xvfb
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: "Install JS dependencies"
        run: npm ci
      - name: "Run JS tests"
        run: xvfb-run npm test

  test-python:
    runs-on: macos-latest  # TODO: FIXME
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"  # matches current Python in production
      - name: "Run Python tests (on Docker)"
        run: |
            make clean test-image
        # FIXME: add back coverage
